// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: sso.proto

package server

import (
	"context"

	"github.com/krace-tx/emo_trash/app/rpc/sso/internal/logic/auth"
	"github.com/krace-tx/emo_trash/app/rpc/sso/internal/svc"
	"github.com/krace-tx/emo_trash/app/rpc/sso/pb"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

// 发送邮箱验证码
func (s *AuthServer) SendEmailCode(ctx context.Context, in *pb.SendEmailCodeReq) (*pb.SendEmailCodeResp, error) {
	l := authlogic.NewSendEmailCodeLogic(ctx, s.svcCtx)
	return l.SendEmailCode(in)
}

// 邮箱注册
func (s *AuthServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.LoginResp, error) {
	l := authlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 邮箱登录
func (s *AuthServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := authlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 忘记密码（通过邮箱验证码重置）
func (s *AuthServer) ResetPassword(ctx context.Context, in *pb.ResetPasswordReq) (*pb.CommonResp, error) {
	l := authlogic.NewResetPasswordLogic(ctx, s.svcCtx)
	return l.ResetPassword(in)
}

// 修改密码（已登录状态，需旧密码验证）
func (s *AuthServer) ChangePassword(ctx context.Context, in *pb.ChangePasswordReq) (*pb.CommonResp, error) {
	l := authlogic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

// 刷新 Token
func (s *AuthServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenReq) (*pb.LoginResp, error) {
	l := authlogic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// 验证会话
func (s *AuthServer) VerifyToken(ctx context.Context, in *pb.VerifyReq) (*pb.VerifyResp, error) {
	l := authlogic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}

// 登出
func (s *AuthServer) Logout(ctx context.Context, in *pb.LogoutReq) (*pb.CommonResp, error) {
	l := authlogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// 获取用户信息
func (s *AuthServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := authlogic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// 更新用户信息
func (s *AuthServer) UpdateUserInfo(ctx context.Context, in *pb.UpdateUserInfoReq) (*pb.CommonResp, error) {
	l := authlogic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

// 获取用户统计
func (s *AuthServer) GetUserStats(ctx context.Context, in *pb.GetUserStatsReq) (*pb.GetUserStatsResp, error) {
	l := authlogic.NewGetUserStatsLogic(ctx, s.svcCtx)
	return l.GetUserStats(in)
}

// 获取每日温柔文案
func (s *AuthServer) GetComfortMessage(ctx context.Context, in *pb.GetComfortMessageReq) (*pb.GetComfortMessageResp, error) {
	l := authlogic.NewGetComfortMessageLogic(ctx, s.svcCtx)
	return l.GetComfortMessage(in)
}

// 三方登录
func (s *AuthServer) LoginByThirdParty(ctx context.Context, in *pb.LoginByThirdPartyReq) (*pb.LoginResp, error) {
	l := authlogic.NewLoginByThirdPartyLogic(ctx, s.svcCtx)
	return l.LoginByThirdParty(in)
}

// 生成二维码
func (s *AuthServer) GenerateQrcode(ctx context.Context, in *pb.GenerateQrcodeReq) (*pb.GenerateQrcodeResp, error) {
	l := authlogic.NewGenerateQrcodeLogic(ctx, s.svcCtx)
	return l.GenerateQrcode(in)
}

// 检查二维码状态
func (s *AuthServer) CheckQrcodeStatus(ctx context.Context, in *pb.CheckQrcodeStatusReq) (*pb.CheckQrcodeStatusResp, error) {
	l := authlogic.NewCheckQrcodeStatusLogic(ctx, s.svcCtx)
	return l.CheckQrcodeStatus(in)
}

// 确认二维码登录
func (s *AuthServer) ConfirmQrcodeLogin(ctx context.Context, in *pb.ConfirmQrcodeLoginReq) (*pb.CommonResp, error) {
	l := authlogic.NewConfirmQrcodeLoginLogic(ctx, s.svcCtx)
	return l.ConfirmQrcodeLogin(in)
}

// 媒体上传
func (s *AuthServer) UploadMedia(ctx context.Context, in *pb.UploadMediaReq) (*pb.UploadMediaResp, error) {
	l := authlogic.NewUploadMediaLogic(ctx, s.svcCtx)
	return l.UploadMedia(in)
}
