// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: sso.proto

package auth

import (
	"context"

	"github.com/krace-tx/emo_trash/app/rpc/sso/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangePasswordReq = pb.ChangePasswordReq
	CommonResp        = pb.CommonResp
	GetUserInfoReq    = pb.GetUserInfoReq
	GetUserInfoResp   = pb.GetUserInfoResp
	LoginReq          = pb.LoginReq
	LoginResp         = pb.LoginResp
	LogoutReq         = pb.LogoutReq
	RefreshTokenReq   = pb.RefreshTokenReq
	RegisterReq       = pb.RegisterReq
	ResetPasswordReq  = pb.ResetPasswordReq
	SendEmailCodeReq  = pb.SendEmailCodeReq
	SendEmailCodeResp = pb.SendEmailCodeResp
	UpdateUserInfoReq = pb.UpdateUserInfoReq
	VerifyReq         = pb.VerifyReq
	VerifyResp        = pb.VerifyResp

	Auth interface {
		// 发送邮箱验证码
		SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeResp, error)
		// 邮箱注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 邮箱登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 忘记密码（通过邮箱验证码重置）
		ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 修改密码（已登录状态，需旧密码验证）
		ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 刷新 Token
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 验证会话
		VerifyToken(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyResp, error)
		// 登出
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 获取用户信息
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// 更新用户信息
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

// 发送邮箱验证码
func (m *defaultAuth) SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.SendEmailCode(ctx, in, opts...)
}

// 邮箱注册
func (m *defaultAuth) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 邮箱登录
func (m *defaultAuth) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 忘记密码（通过邮箱验证码重置）
func (m *defaultAuth) ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.ResetPassword(ctx, in, opts...)
}

// 修改密码（已登录状态，需旧密码验证）
func (m *defaultAuth) ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

// 刷新 Token
func (m *defaultAuth) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// 验证会话
func (m *defaultAuth) VerifyToken(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.VerifyToken(ctx, in, opts...)
}

// 登出
func (m *defaultAuth) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultAuth) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// 更新用户信息
func (m *defaultAuth) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}
