version: '3.8'

services:
  # Redis 缓存服务
  redis:
    image: redis:7.2-alpine
    container_name: emo-trash-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=emoTrashRedis123!
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    networks:
      - emo-trash-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "emoTrashRedis123!", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MySQL 关系型数据库
  mysql:
    image: mysql:8.0
    container_name: emo-trash-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=emoTrashMysql123!
      - MYSQL_DATABASE=emo_trash
      - MYSQL_USER=emo_user
      - MYSQL_PASSWORD=emoUser123!
      - TZ=Asia/Shanghai
    networks:
      - emo-trash-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uemo_user", "-pemoUser123!"]
      interval: 15s
      timeout: 5s
      retries: 3

  # MongoDB 文档数据库
  mongodb:
    image: mongo:6.0
    container_name: emo-trash-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=emoTrashMongo123!
      - MONGO_INITDB_DATABASE=emo_trash
    networks:
      - emo-trash-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "root", "-p", "emoTrashMongo123!"]
      interval: 15s
      timeout: 5s
      retries: 3

  # etcd 分布式配置存储（单节点）
  etcd:
    image: bitnami/etcd:3.6.4
    restart: always  # 总是重启，确保服务持续可用
    ports:
      - "2379:2379"  # 客户端通信端口
      - "2380:2380"  # 节点间通信端口
    environment:
      - ETCDCTL_API=3  # 启用v3 API
      - ETCD_NAME=etcd-node-1  # 节点名称
      - ETCD_DATA_DIR=/etcd-data  # 数据持久化目录
      # 添加etcd根密码（与其他服务密码策略保持一致）
      - ETCD_ROOT_PASSWORD=emoTrashEtcd123!
      # 替换command flags为环境变量配置，避免冲突
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd-node-1=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-token
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd-data:/etcd-data  # 使用命名卷持久化数据
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health", "--endpoints=http://localhost:2379", "--user=root:emoTrashEtcd123!"]
      interval: 10s  # 每10秒检查一次
      timeout: 5s    # 检查超时时间
      retries: 3     # 连续3次失败视为不健康

  # Traefik 反向代理服务
  traefik:
    image: traefik:2.10
    container_name: emo-trash-traefik
    restart: always
    ports:
      - "8080:8080" # Traefik dashboard端口
      - "80:80"      # HTTP入口端口
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
#      - /home/krace/.docker/desktop/docker.sock:/var/run/docker.sock  # 切换到自己的docker.sock
      - /var/run/docker.sock:/var/run/docker.sock  # 切换到自己的docker.sock
    networks:
      - emo-trash-network  # 加入现有网络以与其他服务通信

# 持久化数据卷
volumes:
  redis-data:
  mysql-data:
  mongo-data:
  etcd-data:

# 自定义网络
networks:
  emo-trash-network:
    driver: bridge
    name: emo-trash-network
