// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: chat.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MSG_TYPE_UNKNOWN MessageType = 0
	MessageType_MSG_TYPE_TEXT    MessageType = 1 // 文本
	MessageType_MSG_TYPE_IMAGE   MessageType = 2 // 图片
	MessageType_MSG_TYPE_RECALL  MessageType = 3 // 撤回通知
	MessageType_MSG_TYPE_AI      MessageType = 4 // AI 回复消息
	MessageType_MSG_TYPE_SYSTEM  MessageType = 5 // 系统通知（匹配成功 / 对方已离开等）
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MSG_TYPE_UNKNOWN",
		1: "MSG_TYPE_TEXT",
		2: "MSG_TYPE_IMAGE",
		3: "MSG_TYPE_RECALL",
		4: "MSG_TYPE_AI",
		5: "MSG_TYPE_SYSTEM",
	}
	MessageType_value = map[string]int32{
		"MSG_TYPE_UNKNOWN": 0,
		"MSG_TYPE_TEXT":    1,
		"MSG_TYPE_IMAGE":   2,
		"MSG_TYPE_RECALL":  3,
		"MSG_TYPE_AI":      4,
		"MSG_TYPE_SYSTEM":  5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

type ConversationType int32

const (
	ConversationType_CONV_TYPE_UNKNOWN   ConversationType = 0
	ConversationType_CONV_TYPE_SINGLE    ConversationType = 1 // 普通私聊
	ConversationType_CONV_TYPE_GROUP     ConversationType = 2 // 群聊
	ConversationType_CONV_TYPE_ANONYMOUS ConversationType = 3 // 匿名私聊
	ConversationType_CONV_TYPE_AI        ConversationType = 4 // AI 陪伴会话
)

// Enum value maps for ConversationType.
var (
	ConversationType_name = map[int32]string{
		0: "CONV_TYPE_UNKNOWN",
		1: "CONV_TYPE_SINGLE",
		2: "CONV_TYPE_GROUP",
		3: "CONV_TYPE_ANONYMOUS",
		4: "CONV_TYPE_AI",
	}
	ConversationType_value = map[string]int32{
		"CONV_TYPE_UNKNOWN":   0,
		"CONV_TYPE_SINGLE":    1,
		"CONV_TYPE_GROUP":     2,
		"CONV_TYPE_ANONYMOUS": 3,
		"CONV_TYPE_AI":        4,
	}
)

func (x ConversationType) Enum() *ConversationType {
	p := new(ConversationType)
	*p = x
	return p
}

func (x ConversationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[1].Descriptor()
}

func (ConversationType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[1]
}

func (x ConversationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationType.Descriptor instead.
func (ConversationType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

type MatchStatus int32

const (
	MatchStatus_MATCH_STATUS_UNKNOWN  MatchStatus = 0
	MatchStatus_MATCH_STATUS_WAITING  MatchStatus = 1 // 等待中
	MatchStatus_MATCH_STATUS_MATCHED  MatchStatus = 2 // 已匹配
	MatchStatus_MATCH_STATUS_CANCELED MatchStatus = 3 // 已取消
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "MATCH_STATUS_UNKNOWN",
		1: "MATCH_STATUS_WAITING",
		2: "MATCH_STATUS_MATCHED",
		3: "MATCH_STATUS_CANCELED",
	}
	MatchStatus_value = map[string]int32{
		"MATCH_STATUS_UNKNOWN":  0,
		"MATCH_STATUS_WAITING":  1,
		"MATCH_STATUS_MATCHED":  2,
		"MATCH_STATUS_CANCELED": 3,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[2].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[2]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

// 情感极性（决策层输出）
type EmotionPolarity int32

const (
	EmotionPolarity_EMOTION_UNKNOWN  EmotionPolarity = 0
	EmotionPolarity_EMOTION_POSITIVE EmotionPolarity = 1 // 积极
	EmotionPolarity_EMOTION_NEUTRAL  EmotionPolarity = 2 // 中性
	EmotionPolarity_EMOTION_NEGATIVE EmotionPolarity = 3 // 消极
	EmotionPolarity_EMOTION_CRISIS   EmotionPolarity = 4 // 危机（需触发高优先级干预策略）
)

// Enum value maps for EmotionPolarity.
var (
	EmotionPolarity_name = map[int32]string{
		0: "EMOTION_UNKNOWN",
		1: "EMOTION_POSITIVE",
		2: "EMOTION_NEUTRAL",
		3: "EMOTION_NEGATIVE",
		4: "EMOTION_CRISIS",
	}
	EmotionPolarity_value = map[string]int32{
		"EMOTION_UNKNOWN":  0,
		"EMOTION_POSITIVE": 1,
		"EMOTION_NEUTRAL":  2,
		"EMOTION_NEGATIVE": 3,
		"EMOTION_CRISIS":   4,
	}
)

func (x EmotionPolarity) Enum() *EmotionPolarity {
	p := new(EmotionPolarity)
	*p = x
	return p
}

func (x EmotionPolarity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmotionPolarity) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[3].Descriptor()
}

func (EmotionPolarity) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[3]
}

func (x EmotionPolarity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmotionPolarity.Descriptor instead.
func (EmotionPolarity) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

type GroupMemberRole int32

const (
	GroupMemberRole_ROLE_MEMBER GroupMemberRole = 0
	GroupMemberRole_ROLE_ADMIN  GroupMemberRole = 1
	GroupMemberRole_ROLE_OWNER  GroupMemberRole = 2
)

// Enum value maps for GroupMemberRole.
var (
	GroupMemberRole_name = map[int32]string{
		0: "ROLE_MEMBER",
		1: "ROLE_ADMIN",
		2: "ROLE_OWNER",
	}
	GroupMemberRole_value = map[string]int32{
		"ROLE_MEMBER": 0,
		"ROLE_ADMIN":  1,
		"ROLE_OWNER":  2,
	}
)

func (x GroupMemberRole) Enum() *GroupMemberRole {
	p := new(GroupMemberRole)
	*p = x
	return p
}

func (x GroupMemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupMemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[4].Descriptor()
}

func (GroupMemberRole) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[4]
}

func (x GroupMemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupMemberRole.Descriptor instead.
func (GroupMemberRole) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"msg_id"
	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @inject_tag: json:"sender_id"
	SenderId int64 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id"`
	// @inject_tag: json:"type"
	Type MessageType `protobuf:"varint,4,opt,name=type,proto3,enum=chat.MessageType" json:"type"`
	// @inject_tag: json:"content"
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content"` // 文本内容 / 图片URL / 系统提示文案
	// @inject_tag: json:"quote_msg_id"
	QuoteMsgId int64 `protobuf:"varint,6,opt,name=quote_msg_id,json=quoteMsgId,proto3" json:"quote_msg_id"` // 引用回复，0 表示无
	// @inject_tag: json:"is_recalled"
	IsRecalled bool `protobuf:"varint,7,opt,name=is_recalled,json=isRecalled,proto3" json:"is_recalled"`
	// @inject_tag: json:"send_time"
	SendTime      int64 `protobuf:"varint,8,opt,name=send_time,json=sendTime,proto3" json:"send_time"` // Unix 毫秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Message) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_TYPE_UNKNOWN
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetQuoteMsgId() int64 {
	if x != nil {
		return x.QuoteMsgId
	}
	return 0
}

func (x *Message) GetIsRecalled() bool {
	if x != nil {
		return x.IsRecalled
	}
	return false
}

func (x *Message) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type Conversation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @inject_tag: json:"type"
	Type ConversationType `protobuf:"varint,2,opt,name=type,proto3,enum=chat.ConversationType" json:"type"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"` // 群名 / 对方昵称 / "匿名用户" / "AI助手"
	// @inject_tag: json:"avatar"
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
	// @inject_tag: json:"last_message"
	LastMessage *Message `protobuf:"bytes,5,opt,name=last_message,json=lastMessage,proto3" json:"last_message"`
	// @inject_tag: json:"unread_count"
	UnreadCount int32 `protobuf:"varint,6,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count"`
	// @inject_tag: json:"updated_at"
	UpdatedAt     int64 `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Conversation) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *Conversation) GetType() ConversationType {
	if x != nil {
		return x.Type
	}
	return ConversationType_CONV_TYPE_UNKNOWN
}

func (x *Conversation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Conversation) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Conversation) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *Conversation) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Conversation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GroupMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	// @inject_tag: json:"nickname"
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	// @inject_tag: json:"avatar"
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar"`
	// @inject_tag: json:"role"
	Role GroupMemberRole `protobuf:"varint,4,opt,name=role,proto3,enum=chat.GroupMemberRole" json:"role"`
	// @inject_tag: json:"joined_at"
	JoinedAt      int64 `protobuf:"varint,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GroupMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMember) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupMember) GetRole() GroupMemberRole {
	if x != nil {
		return x.Role
	}
	return GroupMemberRole_ROLE_MEMBER
}

func (x *GroupMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type SendMessageReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @inject_tag: json:"type"
	Type MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=chat.MessageType" json:"type"`
	// @inject_tag: json:"content"
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	// @inject_tag: json:"quote_msg_id"
	QuoteMsgId    int64 `protobuf:"varint,4,opt,name=quote_msg_id,json=quoteMsgId,proto3" json:"quote_msg_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendMessageReq) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_TYPE_UNKNOWN
}

func (x *SendMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageReq) GetQuoteMsgId() int64 {
	if x != nil {
		return x.QuoteMsgId
	}
	return 0
}

type SendMessageResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"msg_id"
	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id"`
	// @inject_tag: json:"send_time"
	SendTime      int64 `protobuf:"varint,2,opt,name=send_time,json=sendTime,proto3" json:"send_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageResp) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendMessageResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type GetMessagesReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @inject_tag: json:"before_msg_id"
	BeforeMsgId int64 `protobuf:"varint,2,opt,name=before_msg_id,json=beforeMsgId,proto3" json:"before_msg_id"` // 0 表示从最新一条开始
	// @inject_tag: json:"limit"
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesReq) Reset() {
	*x = GetMessagesReq{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesReq) ProtoMessage() {}

func (x *GetMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesReq.ProtoReflect.Descriptor instead.
func (*GetMessagesReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessagesReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetMessagesReq) GetBeforeMsgId() int64 {
	if x != nil {
		return x.BeforeMsgId
	}
	return 0
}

func (x *GetMessagesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"messages"
	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages"`
	// @inject_tag: json:"has_more"
	HasMore       bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResp) Reset() {
	*x = GetMessagesResp{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResp) ProtoMessage() {}

func (x *GetMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResp.ProtoReflect.Descriptor instead.
func (*GetMessagesResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessagesResp) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type RecallMessageReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"msg_id"
	MsgId         int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallMessageReq) Reset() {
	*x = RecallMessageReq{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallMessageReq) ProtoMessage() {}

func (x *RecallMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallMessageReq.ProtoReflect.Descriptor instead.
func (*RecallMessageReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *RecallMessageReq) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type GetConversationsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"page_size"
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsReq) Reset() {
	*x = GetConversationsReq{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsReq) ProtoMessage() {}

func (x *GetConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsReq.ProtoReflect.Descriptor instead.
func (*GetConversationsReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetConversationsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetConversationsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetConversationsResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"conversations"
	Conversations []*Conversation `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations"`
	// @inject_tag: json:"total"
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsResp) Reset() {
	*x = GetConversationsResp{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsResp) ProtoMessage() {}

func (x *GetConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsResp.ProtoReflect.Descriptor instead.
func (*GetConversationsResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetConversationsResp) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *GetConversationsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MarkReadReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @inject_tag: json:"last_read_msg_id"
	LastReadMsgId int64 `protobuf:"varint,2,opt,name=last_read_msg_id,json=lastReadMsgId,proto3" json:"last_read_msg_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadReq) Reset() {
	*x = MarkReadReq{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReq) ProtoMessage() {}

func (x *MarkReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReq.ProtoReflect.Descriptor instead.
func (*MarkReadReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *MarkReadReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MarkReadReq) GetLastReadMsgId() int64 {
	if x != nil {
		return x.LastReadMsgId
	}
	return 0
}

type CreateGroupReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"avatar"
	Avatar string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar"`
	// @inject_tag: json:"member_ids"
	MemberIds     []int64 `protobuf:"varint,3,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *CreateGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateGroupReq) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateGroupResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"group_id"
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateGroupResp) Reset() {
	*x = CreateGroupResp{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResp) ProtoMessage() {}

func (x *CreateGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResp.ProtoReflect.Descriptor instead.
func (*CreateGroupResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *CreateGroupResp) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupResp) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

type GetGroupInfoReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"group_id"
	GroupId       int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoReq) Reset() {
	*x = GetGroupInfoReq{}
	mi := &file_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoReq) ProtoMessage() {}

func (x *GetGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoReq.ProtoReflect.Descriptor instead.
func (*GetGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *GetGroupInfoReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupInfoResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"group_id"
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"avatar"
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar"`
	// @inject_tag: json:"announcement"
	Announcement string `protobuf:"bytes,4,opt,name=announcement,proto3" json:"announcement"`
	// @inject_tag: json:"owner_id"
	OwnerId int64 `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id"`
	// @inject_tag: json:"member_count"
	MemberCount int32 `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count"`
	// @inject_tag: json:"created_at"
	CreatedAt     int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoResp) Reset() {
	*x = GetGroupInfoResp{}
	mi := &file_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoResp) ProtoMessage() {}

func (x *GetGroupInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoResp.ProtoReflect.Descriptor instead.
func (*GetGroupInfoResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *GetGroupInfoResp) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupInfoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGroupInfoResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetGroupInfoResp) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

func (x *GetGroupInfoResp) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetGroupInfoResp) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GetGroupInfoResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type UpdateGroupInfoReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"group_id"
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"avatar"
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar"`
	// @inject_tag: json:"announcement"
	Announcement  string `protobuf:"bytes,4,opt,name=announcement,proto3" json:"announcement"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupInfoReq) Reset() {
	*x = UpdateGroupInfoReq{}
	mi := &file_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoReq) ProtoMessage() {}

func (x *UpdateGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateGroupInfoReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

type InviteGroupMembersReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"group_id"
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	// @inject_tag: json:"member_ids"
	MemberIds     []int64 `protobuf:"varint,2,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteGroupMembersReq) Reset() {
	*x = InviteGroupMembersReq{}
	mi := &file_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteGroupMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteGroupMembersReq) ProtoMessage() {}

func (x *InviteGroupMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteGroupMembersReq.ProtoReflect.Descriptor instead.
func (*InviteGroupMembersReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{16}
}

func (x *InviteGroupMembersReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *InviteGroupMembersReq) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type QuitGroupReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"group_id"
	GroupId       int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitGroupReq) Reset() {
	*x = QuitGroupReq{}
	mi := &file_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitGroupReq) ProtoMessage() {}

func (x *QuitGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitGroupReq.ProtoReflect.Descriptor instead.
func (*QuitGroupReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{17}
}

func (x *QuitGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type DismissGroupReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"group_id"
	GroupId       int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupReq) Reset() {
	*x = DismissGroupReq{}
	mi := &file_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupReq) ProtoMessage() {}

func (x *DismissGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupReq.ProtoReflect.Descriptor instead.
func (*DismissGroupReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{18}
}

func (x *DismissGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupMembersReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"group_id"
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"page_size"
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersReq) Reset() {
	*x = GetGroupMembersReq{}
	mi := &file_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersReq) ProtoMessage() {}

func (x *GetGroupMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersReq.ProtoReflect.Descriptor instead.
func (*GetGroupMembersReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{19}
}

func (x *GetGroupMembersReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupMembersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupMembersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetGroupMembersResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"members"
	Members []*GroupMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members"`
	// @inject_tag: json:"total"
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersResp) Reset() {
	*x = GetGroupMembersResp{}
	mi := &file_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersResp) ProtoMessage() {}

func (x *GetGroupMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersResp.ProtoReflect.Descriptor instead.
func (*GetGroupMembersResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{20}
}

func (x *GetGroupMembersResp) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetGroupMembersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StartMatchReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"emotion_tag"
	EmotionTag    string `protobuf:"bytes,1,opt,name=emotion_tag,json=emotionTag,proto3" json:"emotion_tag"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchReq) Reset() {
	*x = StartMatchReq{}
	mi := &file_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchReq) ProtoMessage() {}

func (x *StartMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchReq.ProtoReflect.Descriptor instead.
func (*StartMatchReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{21}
}

func (x *StartMatchReq) GetEmotionTag() string {
	if x != nil {
		return x.EmotionTag
	}
	return ""
}

type StartMatchResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"match_id"
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id"` // 匹配任务 ID，用于后续查询状态
	// @inject_tag: json:"status"
	Status MatchStatus `protobuf:"varint,2,opt,name=status,proto3,enum=chat.MatchStatus" json:"status"`
	// @inject_tag: json:"queue_position"
	QueuePosition int32 `protobuf:"varint,3,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position"` // 当前排队位置，供前端展示
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchResp) Reset() {
	*x = StartMatchResp{}
	mi := &file_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchResp) ProtoMessage() {}

func (x *StartMatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchResp.ProtoReflect.Descriptor instead.
func (*StartMatchResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{22}
}

func (x *StartMatchResp) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *StartMatchResp) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNKNOWN
}

func (x *StartMatchResp) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

type CancelMatchReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"match_id"
	MatchId       string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchReq) Reset() {
	*x = CancelMatchReq{}
	mi := &file_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchReq) ProtoMessage() {}

func (x *CancelMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchReq.ProtoReflect.Descriptor instead.
func (*CancelMatchReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{23}
}

func (x *CancelMatchReq) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type GetMatchStatusReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"match_id"
	MatchId       string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchStatusReq) Reset() {
	*x = GetMatchStatusReq{}
	mi := &file_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchStatusReq) ProtoMessage() {}

func (x *GetMatchStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchStatusReq.ProtoReflect.Descriptor instead.
func (*GetMatchStatusReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{24}
}

func (x *GetMatchStatusReq) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type GetMatchStatusResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"status"
	Status MatchStatus `protobuf:"varint,1,opt,name=status,proto3,enum=chat.MatchStatus" json:"status"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"` // 匹配成功后返回，status=MATCHED 时有效
	// @inject_tag: json:"anonymous_name"
	AnonymousName string `protobuf:"bytes,3,opt,name=anonymous_name,json=anonymousName,proto3" json:"anonymous_name"` // 对方的随机匿名昵称，如"流浪的星球#4721"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchStatusResp) Reset() {
	*x = GetMatchStatusResp{}
	mi := &file_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchStatusResp) ProtoMessage() {}

func (x *GetMatchStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchStatusResp.ProtoReflect.Descriptor instead.
func (*GetMatchStatusResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{25}
}

func (x *GetMatchStatusResp) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNKNOWN
}

func (x *GetMatchStatusResp) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetMatchStatusResp) GetAnonymousName() string {
	if x != nil {
		return x.AnonymousName
	}
	return ""
}

type EndAnonymousChatReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EndAnonymousChatReq) Reset() {
	*x = EndAnonymousChatReq{}
	mi := &file_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndAnonymousChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndAnonymousChatReq) ProtoMessage() {}

func (x *EndAnonymousChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndAnonymousChatReq.ProtoReflect.Descriptor instead.
func (*EndAnonymousChatReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{26}
}

func (x *EndAnonymousChatReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

type SendToAIReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @inject_tag: json:"content"
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToAIReq) Reset() {
	*x = SendToAIReq{}
	mi := &file_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToAIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToAIReq) ProtoMessage() {}

func (x *SendToAIReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToAIReq.ProtoReflect.Descriptor instead.
func (*SendToAIReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{27}
}

func (x *SendToAIReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendToAIReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendToAIResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"msg_id"
	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id"`
	// @inject_tag: json:"reply"
	Reply string `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply"` // AI 输出层生成的安抚性回复
	// @inject_tag: json:"emotion"
	Emotion *EmotionAnalysisResult `protobuf:"bytes,3,opt,name=emotion,proto3" json:"emotion"` // 决策层分析结果，供前端动态 UI 使用
	// @inject_tag: json:"send_time"
	SendTime      int64 `protobuf:"varint,4,opt,name=send_time,json=sendTime,proto3" json:"send_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToAIResp) Reset() {
	*x = SendToAIResp{}
	mi := &file_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToAIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToAIResp) ProtoMessage() {}

func (x *SendToAIResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToAIResp.ProtoReflect.Descriptor instead.
func (*SendToAIResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{28}
}

func (x *SendToAIResp) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendToAIResp) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *SendToAIResp) GetEmotion() *EmotionAnalysisResult {
	if x != nil {
		return x.Emotion
	}
	return nil
}

func (x *SendToAIResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type GetAIHistoryReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"conversation_id"
	ConversationId int64 `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @inject_tag: json:"before_msg_id"
	BeforeMsgId int64 `protobuf:"varint,2,opt,name=before_msg_id,json=beforeMsgId,proto3" json:"before_msg_id"`
	// @inject_tag: json:"limit"
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAIHistoryReq) Reset() {
	*x = GetAIHistoryReq{}
	mi := &file_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAIHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIHistoryReq) ProtoMessage() {}

func (x *GetAIHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIHistoryReq.ProtoReflect.Descriptor instead.
func (*GetAIHistoryReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{29}
}

func (x *GetAIHistoryReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetAIHistoryReq) GetBeforeMsgId() int64 {
	if x != nil {
		return x.BeforeMsgId
	}
	return 0
}

func (x *GetAIHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAIHistoryResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"messages"
	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages"`
	// @inject_tag: json:"has_more"
	HasMore       bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAIHistoryResp) Reset() {
	*x = GetAIHistoryResp{}
	mi := &file_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAIHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIHistoryResp) ProtoMessage() {}

func (x *GetAIHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIHistoryResp.ProtoReflect.Descriptor instead.
func (*GetAIHistoryResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{30}
}

func (x *GetAIHistoryResp) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetAIHistoryResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetEmotionAnalysisReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"msg_id"
	MsgId         int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmotionAnalysisReq) Reset() {
	*x = GetEmotionAnalysisReq{}
	mi := &file_chat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmotionAnalysisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmotionAnalysisReq) ProtoMessage() {}

func (x *GetEmotionAnalysisReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmotionAnalysisReq.ProtoReflect.Descriptor instead.
func (*GetEmotionAnalysisReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{31}
}

func (x *GetEmotionAnalysisReq) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type GetEmotionAnalysisResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"result"
	Result        *EmotionAnalysisResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmotionAnalysisResp) Reset() {
	*x = GetEmotionAnalysisResp{}
	mi := &file_chat_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmotionAnalysisResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmotionAnalysisResp) ProtoMessage() {}

func (x *GetEmotionAnalysisResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmotionAnalysisResp.ProtoReflect.Descriptor instead.
func (*GetEmotionAnalysisResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{32}
}

func (x *GetEmotionAnalysisResp) GetResult() *EmotionAnalysisResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// 情感分析结果（决策层输出，复用于多处）
type EmotionAnalysisResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"polarity"
	Polarity EmotionPolarity `protobuf:"varint,1,opt,name=polarity,proto3,enum=chat.EmotionPolarity" json:"polarity"` // 情感极性
	// @inject_tag: json:"score"
	Score float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score"` // 置信度 0.0-1.0
	// @inject_tag: json:"keywords"
	Keywords []string `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords"` // 识别到的情绪关键词
	// @inject_tag: json:"intervention_level"
	InterventionLevel int32 `protobuf:"varint,4,opt,name=intervention_level,json=interventionLevel,proto3" json:"intervention_level"` // 干预等级 1-3，供输出层选择回复策略
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmotionAnalysisResult) Reset() {
	*x = EmotionAnalysisResult{}
	mi := &file_chat_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionAnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionAnalysisResult) ProtoMessage() {}

func (x *EmotionAnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionAnalysisResult.ProtoReflect.Descriptor instead.
func (*EmotionAnalysisResult) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{33}
}

func (x *EmotionAnalysisResult) GetPolarity() EmotionPolarity {
	if x != nil {
		return x.Polarity
	}
	return EmotionPolarity_EMOTION_UNKNOWN
}

func (x *EmotionAnalysisResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EmotionAnalysisResult) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *EmotionAnalysisResult) GetInterventionLevel() int32 {
	if x != nil {
		return x.InterventionLevel
	}
	return 0
}

type CommonResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_chat_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{34}
}

func (x *CommonResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x04chat\x1a\x17validate/validate.proto\"\x87\x02\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.chat.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12 \n" +
	"\fquote_msg_id\x18\x06 \x01(\x03R\n" +
	"quoteMsgId\x12\x1f\n" +
	"\vis_recalled\x18\a \x01(\bR\n" +
	"isRecalled\x12\x1b\n" +
	"\tsend_time\x18\b \x01(\x03R\bsendTime\"\x83\x02\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.chat.ConversationTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x120\n" +
	"\flast_message\x18\x05 \x01(\v2\r.chat.MessageR\vlastMessage\x12!\n" +
	"\funread_count\x18\x06 \x01(\x05R\vunreadCount\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xa2\x01\n" +
	"\vGroupMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12)\n" +
	"\x04role\x18\x04 \x01(\x0e2\x15.chat.GroupMemberRoleR\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\x03R\bjoinedAt\"\xcf\x02\n" +
	"\x0eSendMessageReq\x12J\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03B!\xfaB\x04\"\x02 \x00\x82\xb5\x18\x16conversation_id 无效R\x0econversationId\x12u\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.chat.MessageTypeBN\xfaB\r\x82\x01\n" +
	"\x10\x01 \x00 \x03 \x04 \x05\x82\xb5\x18:消息类型无效，客户端只允许发送 TEXT / IMAGER\x04type\x12X\n" +
	"\acontent\x18\x03 \x01(\tB>\xfaB\ar\x05\x10\x01\x18\xd0\x0f\x82\xb5\x180消息内容不能为空且不超过 2000 字符R\acontent\x12 \n" +
	"\fquote_msg_id\x18\x04 \x01(\x03R\n" +
	"quoteMsgId\"E\n" +
	"\x0fSendMessageResp\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x1b\n" +
	"\tsend_time\x18\x02 \x01(\x03R\bsendTime\"\xb9\x01\n" +
	"\x0eGetMessagesReq\x12J\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03B!\xfaB\x04\"\x02 \x00\x82\xb5\x18\x16conversation_id 无效R\x0econversationId\x12\"\n" +
	"\rbefore_msg_id\x18\x02 \x01(\x03R\vbeforeMsgId\x127\n" +
	"\x05limit\x18\x03 \x01(\x05B!\xfaB\x06\x1a\x04\x182(\x01\x82\xb5\x18\x14limit 范围为 1-50R\x05limit\"W\n" +
	"\x0fGetMessagesResp\x12)\n" +
	"\bmessages\x18\x01 \x03(\v2\r.chat.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"C\n" +
	"\x10RecallMessageReq\x12/\n" +
	"\x06msg_id\x18\x01 \x01(\x03B\x18\xfaB\x04\"\x02 \x00\x82\xb5\x18\rmsg_id 无效R\x05msgId\"\x8a\x01\n" +
	"\x13GetConversationsReq\x12/\n" +
	"\x04page\x18\x01 \x01(\x05B\x1b\xfaB\x04\x1a\x02(\x01\x82\xb5\x18\x10page 最小为 1R\x04page\x12B\n" +
	"\tpage_size\x18\x02 \x01(\x05B%\xfaB\x06\x1a\x04\x18\x1e(\x01\x82\xb5\x18\x18page_size 范围为 1-30R\bpageSize\"f\n" +
	"\x14GetConversationsResp\x128\n" +
	"\rconversations\x18\x01 \x03(\v2\x12.chat.ConversationR\rconversations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa6\x01\n" +
	"\vMarkReadReq\x12J\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03B!\xfaB\x04\"\x02 \x00\x82\xb5\x18\x16conversation_id 无效R\x0econversationId\x12K\n" +
	"\x10last_read_msg_id\x18\x02 \x01(\x03B\"\xfaB\x04\"\x02 \x00\x82\xb5\x18\x17last_read_msg_id 无效R\rlastReadMsgId\"\xb9\x01\n" +
	"\x0eCreateGroupReq\x12<\n" +
	"\x04name\x18\x01 \x01(\tB(\xfaB\x06r\x04\x10\x02\x18\x1e\x82\xb5\x18\x1b群名长度为 2-30 字符R\x04name\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12Q\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\x03B2\xfaB\a\x92\x01\x04\b\x02\x10c\x82\xb5\x18$建群至少需要邀请 2 名成员R\tmemberIds\"U\n" +
	"\x0fCreateGroupResp\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\"H\n" +
	"\x0fGetGroupInfoReq\x125\n" +
	"\bgroup_id\x18\x01 \x01(\x03B\x1a\xfaB\x04\"\x02 \x00\x82\xb5\x18\x0fgroup_id 无效R\agroupId\"\xda\x01\n" +
	"\x10GetGroupInfoResp\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\"\n" +
	"\fannouncement\x18\x04 \x01(\tR\fannouncement\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\x03R\aownerId\x12!\n" +
	"\fmember_count\x18\x06 \x01(\x05R\vmemberCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xe6\x01\n" +
	"\x12UpdateGroupInfoReq\x125\n" +
	"\bgroup_id\x18\x01 \x01(\x03B\x1a\xfaB\x04\"\x02 \x00\x82\xb5\x18\x0fgroup_id 无效R\agroupId\x125\n" +
	"\x04name\x18\x02 \x01(\tB!\xfaB\x04r\x02\x18\x1e\x82\xb5\x18\x16群名最长 30 字符R\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12J\n" +
	"\fannouncement\x18\x04 \x01(\tB&\xfaB\x05r\x03\x18\xac\x02\x82\xb5\x18\x1a群公告最长 300 字符R\fannouncement\"\x92\x01\n" +
	"\x15InviteGroupMembersReq\x125\n" +
	"\bgroup_id\x18\x01 \x01(\x03B\x1a\xfaB\x04\"\x02 \x00\x82\xb5\x18\x0fgroup_id 无效R\agroupId\x12B\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\x03B#\xfaB\a\x92\x01\x04\b\x01\x102\x82\xb5\x18\x15每次邀请 1-50 人R\tmemberIds\"E\n" +
	"\fQuitGroupReq\x125\n" +
	"\bgroup_id\x18\x01 \x01(\x03B\x1a\xfaB\x04\"\x02 \x00\x82\xb5\x18\x0fgroup_id 无效R\agroupId\"H\n" +
	"\x0fDismissGroupReq\x125\n" +
	"\bgroup_id\x18\x01 \x01(\x03B\x1a\xfaB\x04\"\x02 \x00\x82\xb5\x18\x0fgroup_id 无效R\agroupId\"\xc1\x01\n" +
	"\x12GetGroupMembersReq\x125\n" +
	"\bgroup_id\x18\x01 \x01(\x03B\x1a\xfaB\x04\"\x02 \x00\x82\xb5\x18\x0fgroup_id 无效R\agroupId\x12/\n" +
	"\x04page\x18\x02 \x01(\x05B\x1b\xfaB\x04\x1a\x02(\x01\x82\xb5\x18\x10page 最小为 1R\x04page\x12C\n" +
	"\tpage_size\x18\x03 \x01(\x05B&\xfaB\x06\x1a\x04\x18d(\x01\x82\xb5\x18\x19page_size 范围为 1-100R\bpageSize\"X\n" +
	"\x13GetGroupMembersResp\x12+\n" +
	"\amembers\x18\x01 \x03(\v2\x11.chat.GroupMemberR\amembers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa9\x01\n" +
	"\rStartMatchReq\x12\x97\x01\n" +
	"\vemotion_tag\x18\x01 \x01(\tBv\xfaB-r+R\x06lonelyR\aanxiousR\bstressedR\x03sadR\tjust_chat\x82\xb5\x18B情绪标签无效，支持: lonely/anxious/stressed/sad/just_chatR\n" +
	"emotionTag\"}\n" +
	"\x0eStartMatchResp\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.chat.MatchStatusR\x06status\x12%\n" +
	"\x0equeue_position\x18\x03 \x01(\x05R\rqueuePosition\"M\n" +
	"\x0eCancelMatchReq\x12;\n" +
	"\bmatch_id\x18\x01 \x01(\tB \xfaB\x04r\x02\x10\x01\x82\xb5\x18\x15match_id 不能为空R\amatchId\"P\n" +
	"\x11GetMatchStatusReq\x12;\n" +
	"\bmatch_id\x18\x01 \x01(\tB \xfaB\x04r\x02\x10\x01\x82\xb5\x18\x15match_id 不能为空R\amatchId\"\x8f\x01\n" +
	"\x12GetMatchStatusResp\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.chat.MatchStatusR\x06status\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12%\n" +
	"\x0eanonymous_name\x18\x03 \x01(\tR\ranonymousName\"a\n" +
	"\x13EndAnonymousChatReq\x12J\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03B!\xfaB\x04\"\x02 \x00\x82\xb5\x18\x16conversation_id 无效R\x0econversationId\"\xad\x01\n" +
	"\vSendToAIReq\x12J\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03B!\xfaB\x04\"\x02 \x00\x82\xb5\x18\x16conversation_id 无效R\x0econversationId\x12R\n" +
	"\acontent\x18\x02 \x01(\tB8\xfaB\ar\x05\x10\x01\x18\xe8\a\x82\xb5\x18*内容不能为空且不超过 1000 字符R\acontent\"\x8f\x01\n" +
	"\fSendToAIResp\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x14\n" +
	"\x05reply\x18\x02 \x01(\tR\x05reply\x125\n" +
	"\aemotion\x18\x03 \x01(\v2\x1b.chat.EmotionAnalysisResultR\aemotion\x12\x1b\n" +
	"\tsend_time\x18\x04 \x01(\x03R\bsendTime\"\xba\x01\n" +
	"\x0fGetAIHistoryReq\x12J\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03B!\xfaB\x04\"\x02 \x00\x82\xb5\x18\x16conversation_id 无效R\x0econversationId\x12\"\n" +
	"\rbefore_msg_id\x18\x02 \x01(\x03R\vbeforeMsgId\x127\n" +
	"\x05limit\x18\x03 \x01(\x05B!\xfaB\x06\x1a\x04\x18\x1e(\x01\x82\xb5\x18\x14limit 范围为 1-30R\x05limit\"X\n" +
	"\x10GetAIHistoryResp\x12)\n" +
	"\bmessages\x18\x01 \x03(\v2\r.chat.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"H\n" +
	"\x15GetEmotionAnalysisReq\x12/\n" +
	"\x06msg_id\x18\x01 \x01(\x03B\x18\xfaB\x04\"\x02 \x00\x82\xb5\x18\rmsg_id 无效R\x05msgId\"M\n" +
	"\x16GetEmotionAnalysisResp\x123\n" +
	"\x06result\x18\x01 \x01(\v2\x1b.chat.EmotionAnalysisResultR\x06result\"\xab\x01\n" +
	"\x15EmotionAnalysisResult\x121\n" +
	"\bpolarity\x18\x01 \x01(\x0e2\x15.chat.EmotionPolarityR\bpolarity\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\x12-\n" +
	"\x12intervention_level\x18\x04 \x01(\x05R\x11interventionLevel\"@\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x85\x01\n" +
	"\vMessageType\x12\x14\n" +
	"\x10MSG_TYPE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rMSG_TYPE_TEXT\x10\x01\x12\x12\n" +
	"\x0eMSG_TYPE_IMAGE\x10\x02\x12\x13\n" +
	"\x0fMSG_TYPE_RECALL\x10\x03\x12\x0f\n" +
	"\vMSG_TYPE_AI\x10\x04\x12\x13\n" +
	"\x0fMSG_TYPE_SYSTEM\x10\x05*\x7f\n" +
	"\x10ConversationType\x12\x15\n" +
	"\x11CONV_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10CONV_TYPE_SINGLE\x10\x01\x12\x13\n" +
	"\x0fCONV_TYPE_GROUP\x10\x02\x12\x17\n" +
	"\x13CONV_TYPE_ANONYMOUS\x10\x03\x12\x10\n" +
	"\fCONV_TYPE_AI\x10\x04*v\n" +
	"\vMatchStatus\x12\x18\n" +
	"\x14MATCH_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14MATCH_STATUS_WAITING\x10\x01\x12\x18\n" +
	"\x14MATCH_STATUS_MATCHED\x10\x02\x12\x19\n" +
	"\x15MATCH_STATUS_CANCELED\x10\x03*{\n" +
	"\x0fEmotionPolarity\x12\x13\n" +
	"\x0fEMOTION_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10EMOTION_POSITIVE\x10\x01\x12\x13\n" +
	"\x0fEMOTION_NEUTRAL\x10\x02\x12\x14\n" +
	"\x10EMOTION_NEGATIVE\x10\x03\x12\x12\n" +
	"\x0eEMOTION_CRISIS\x10\x04*B\n" +
	"\x0fGroupMemberRole\x12\x0f\n" +
	"\vROLE_MEMBER\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x022\xa1\t\n" +
	"\x04chat\x12:\n" +
	"\vSendMessage\x12\x14.chat.SendMessageReq\x1a\x15.chat.SendMessageResp\x12:\n" +
	"\vGetMessages\x12\x14.chat.GetMessagesReq\x1a\x15.chat.GetMessagesResp\x129\n" +
	"\rRecallMessage\x12\x16.chat.RecallMessageReq\x1a\x10.chat.CommonResp\x12I\n" +
	"\x10GetConversations\x12\x19.chat.GetConversationsReq\x1a\x1a.chat.GetConversationsResp\x12/\n" +
	"\bMarkRead\x12\x11.chat.MarkReadReq\x1a\x10.chat.CommonResp\x12:\n" +
	"\vCreateGroup\x12\x14.chat.CreateGroupReq\x1a\x15.chat.CreateGroupResp\x12=\n" +
	"\fGetGroupInfo\x12\x15.chat.GetGroupInfoReq\x1a\x16.chat.GetGroupInfoResp\x12=\n" +
	"\x0fUpdateGroupInfo\x12\x18.chat.UpdateGroupInfoReq\x1a\x10.chat.CommonResp\x12C\n" +
	"\x12InviteGroupMembers\x12\x1b.chat.InviteGroupMembersReq\x1a\x10.chat.CommonResp\x121\n" +
	"\tQuitGroup\x12\x12.chat.QuitGroupReq\x1a\x10.chat.CommonResp\x127\n" +
	"\fDismissGroup\x12\x15.chat.DismissGroupReq\x1a\x10.chat.CommonResp\x12F\n" +
	"\x0fGetGroupMembers\x12\x18.chat.GetGroupMembersReq\x1a\x19.chat.GetGroupMembersResp\x127\n" +
	"\n" +
	"StartMatch\x12\x13.chat.StartMatchReq\x1a\x14.chat.StartMatchResp\x125\n" +
	"\vCancelMatch\x12\x14.chat.CancelMatchReq\x1a\x10.chat.CommonResp\x12C\n" +
	"\x0eGetMatchStatus\x12\x17.chat.GetMatchStatusReq\x1a\x18.chat.GetMatchStatusResp\x12?\n" +
	"\x10EndAnonymousChat\x12\x19.chat.EndAnonymousChatReq\x1a\x10.chat.CommonResp\x121\n" +
	"\bSendToAI\x12\x11.chat.SendToAIReq\x1a\x12.chat.SendToAIResp\x12=\n" +
	"\fGetAIHistory\x12\x15.chat.GetAIHistoryReq\x1a\x16.chat.GetAIHistoryResp\x12O\n" +
	"\x12GetEmotionAnalysis\x12\x1b.chat.GetEmotionAnalysisReq\x1a\x1c.chat.GetEmotionAnalysisRespB\x06Z\x04./pbb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_chat_proto_goTypes = []any{
	(MessageType)(0),               // 0: chat.MessageType
	(ConversationType)(0),          // 1: chat.ConversationType
	(MatchStatus)(0),               // 2: chat.MatchStatus
	(EmotionPolarity)(0),           // 3: chat.EmotionPolarity
	(GroupMemberRole)(0),           // 4: chat.GroupMemberRole
	(*Message)(nil),                // 5: chat.Message
	(*Conversation)(nil),           // 6: chat.Conversation
	(*GroupMember)(nil),            // 7: chat.GroupMember
	(*SendMessageReq)(nil),         // 8: chat.SendMessageReq
	(*SendMessageResp)(nil),        // 9: chat.SendMessageResp
	(*GetMessagesReq)(nil),         // 10: chat.GetMessagesReq
	(*GetMessagesResp)(nil),        // 11: chat.GetMessagesResp
	(*RecallMessageReq)(nil),       // 12: chat.RecallMessageReq
	(*GetConversationsReq)(nil),    // 13: chat.GetConversationsReq
	(*GetConversationsResp)(nil),   // 14: chat.GetConversationsResp
	(*MarkReadReq)(nil),            // 15: chat.MarkReadReq
	(*CreateGroupReq)(nil),         // 16: chat.CreateGroupReq
	(*CreateGroupResp)(nil),        // 17: chat.CreateGroupResp
	(*GetGroupInfoReq)(nil),        // 18: chat.GetGroupInfoReq
	(*GetGroupInfoResp)(nil),       // 19: chat.GetGroupInfoResp
	(*UpdateGroupInfoReq)(nil),     // 20: chat.UpdateGroupInfoReq
	(*InviteGroupMembersReq)(nil),  // 21: chat.InviteGroupMembersReq
	(*QuitGroupReq)(nil),           // 22: chat.QuitGroupReq
	(*DismissGroupReq)(nil),        // 23: chat.DismissGroupReq
	(*GetGroupMembersReq)(nil),     // 24: chat.GetGroupMembersReq
	(*GetGroupMembersResp)(nil),    // 25: chat.GetGroupMembersResp
	(*StartMatchReq)(nil),          // 26: chat.StartMatchReq
	(*StartMatchResp)(nil),         // 27: chat.StartMatchResp
	(*CancelMatchReq)(nil),         // 28: chat.CancelMatchReq
	(*GetMatchStatusReq)(nil),      // 29: chat.GetMatchStatusReq
	(*GetMatchStatusResp)(nil),     // 30: chat.GetMatchStatusResp
	(*EndAnonymousChatReq)(nil),    // 31: chat.EndAnonymousChatReq
	(*SendToAIReq)(nil),            // 32: chat.SendToAIReq
	(*SendToAIResp)(nil),           // 33: chat.SendToAIResp
	(*GetAIHistoryReq)(nil),        // 34: chat.GetAIHistoryReq
	(*GetAIHistoryResp)(nil),       // 35: chat.GetAIHistoryResp
	(*GetEmotionAnalysisReq)(nil),  // 36: chat.GetEmotionAnalysisReq
	(*GetEmotionAnalysisResp)(nil), // 37: chat.GetEmotionAnalysisResp
	(*EmotionAnalysisResult)(nil),  // 38: chat.EmotionAnalysisResult
	(*CommonResp)(nil),             // 39: chat.CommonResp
}
var file_chat_proto_depIdxs = []int32{
	0,  // 0: chat.Message.type:type_name -> chat.MessageType
	1,  // 1: chat.Conversation.type:type_name -> chat.ConversationType
	5,  // 2: chat.Conversation.last_message:type_name -> chat.Message
	4,  // 3: chat.GroupMember.role:type_name -> chat.GroupMemberRole
	0,  // 4: chat.SendMessageReq.type:type_name -> chat.MessageType
	5,  // 5: chat.GetMessagesResp.messages:type_name -> chat.Message
	6,  // 6: chat.GetConversationsResp.conversations:type_name -> chat.Conversation
	7,  // 7: chat.GetGroupMembersResp.members:type_name -> chat.GroupMember
	2,  // 8: chat.StartMatchResp.status:type_name -> chat.MatchStatus
	2,  // 9: chat.GetMatchStatusResp.status:type_name -> chat.MatchStatus
	38, // 10: chat.SendToAIResp.emotion:type_name -> chat.EmotionAnalysisResult
	5,  // 11: chat.GetAIHistoryResp.messages:type_name -> chat.Message
	38, // 12: chat.GetEmotionAnalysisResp.result:type_name -> chat.EmotionAnalysisResult
	3,  // 13: chat.EmotionAnalysisResult.polarity:type_name -> chat.EmotionPolarity
	8,  // 14: chat.chat.SendMessage:input_type -> chat.SendMessageReq
	10, // 15: chat.chat.GetMessages:input_type -> chat.GetMessagesReq
	12, // 16: chat.chat.RecallMessage:input_type -> chat.RecallMessageReq
	13, // 17: chat.chat.GetConversations:input_type -> chat.GetConversationsReq
	15, // 18: chat.chat.MarkRead:input_type -> chat.MarkReadReq
	16, // 19: chat.chat.CreateGroup:input_type -> chat.CreateGroupReq
	18, // 20: chat.chat.GetGroupInfo:input_type -> chat.GetGroupInfoReq
	20, // 21: chat.chat.UpdateGroupInfo:input_type -> chat.UpdateGroupInfoReq
	21, // 22: chat.chat.InviteGroupMembers:input_type -> chat.InviteGroupMembersReq
	22, // 23: chat.chat.QuitGroup:input_type -> chat.QuitGroupReq
	23, // 24: chat.chat.DismissGroup:input_type -> chat.DismissGroupReq
	24, // 25: chat.chat.GetGroupMembers:input_type -> chat.GetGroupMembersReq
	26, // 26: chat.chat.StartMatch:input_type -> chat.StartMatchReq
	28, // 27: chat.chat.CancelMatch:input_type -> chat.CancelMatchReq
	29, // 28: chat.chat.GetMatchStatus:input_type -> chat.GetMatchStatusReq
	31, // 29: chat.chat.EndAnonymousChat:input_type -> chat.EndAnonymousChatReq
	32, // 30: chat.chat.SendToAI:input_type -> chat.SendToAIReq
	34, // 31: chat.chat.GetAIHistory:input_type -> chat.GetAIHistoryReq
	36, // 32: chat.chat.GetEmotionAnalysis:input_type -> chat.GetEmotionAnalysisReq
	9,  // 33: chat.chat.SendMessage:output_type -> chat.SendMessageResp
	11, // 34: chat.chat.GetMessages:output_type -> chat.GetMessagesResp
	39, // 35: chat.chat.RecallMessage:output_type -> chat.CommonResp
	14, // 36: chat.chat.GetConversations:output_type -> chat.GetConversationsResp
	39, // 37: chat.chat.MarkRead:output_type -> chat.CommonResp
	17, // 38: chat.chat.CreateGroup:output_type -> chat.CreateGroupResp
	19, // 39: chat.chat.GetGroupInfo:output_type -> chat.GetGroupInfoResp
	39, // 40: chat.chat.UpdateGroupInfo:output_type -> chat.CommonResp
	39, // 41: chat.chat.InviteGroupMembers:output_type -> chat.CommonResp
	39, // 42: chat.chat.QuitGroup:output_type -> chat.CommonResp
	39, // 43: chat.chat.DismissGroup:output_type -> chat.CommonResp
	25, // 44: chat.chat.GetGroupMembers:output_type -> chat.GetGroupMembersResp
	27, // 45: chat.chat.StartMatch:output_type -> chat.StartMatchResp
	39, // 46: chat.chat.CancelMatch:output_type -> chat.CommonResp
	30, // 47: chat.chat.GetMatchStatus:output_type -> chat.GetMatchStatusResp
	39, // 48: chat.chat.EndAnonymousChat:output_type -> chat.CommonResp
	33, // 49: chat.chat.SendToAI:output_type -> chat.SendToAIResp
	35, // 50: chat.chat.GetAIHistory:output_type -> chat.GetAIHistoryResp
	37, // 51: chat.chat.GetEmotionAnalysis:output_type -> chat.GetEmotionAnalysisResp
	33, // [33:52] is the sub-list for method output_type
	14, // [14:33] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
