// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: post.proto

package post

import (
	"context"

	"github.com/krace-tx/emo_trash/app/rpc/post/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp        = pb.CommonResp
	CreatePostReq     = pb.CreatePostReq
	CreatePostResp    = pb.CreatePostResp
	DeletePostReq     = pb.DeletePostReq
	GetPostDetailReq  = pb.GetPostDetailReq
	GetPostDetailResp = pb.GetPostDetailResp
	LikePostReq       = pb.LikePostReq
	ListPostsReq      = pb.ListPostsReq
	ListPostsResp     = pb.ListPostsResp
	StarPostReq       = pb.StarPostReq
	UpdatePostReq     = pb.UpdatePostReq

	Post interface {
		// 发布帖子
		CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error)
		// 更新帖子
		UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 删除帖子
		DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 获取帖子详情
		GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error)
		// 帖子列表
		ListPosts(ctx context.Context, in *ListPostsReq, opts ...grpc.CallOption) (*ListPostsResp, error)
		// 点赞/取消点赞
		LikePost(ctx context.Context, in *LikePostReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 收藏/取消收藏
		StarPost(ctx context.Context, in *StarPostReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultPost struct {
		cli zrpc.Client
	}
)

func NewPost(cli zrpc.Client) Post {
	return &defaultPost{
		cli: cli,
	}
}

// 发布帖子
func (m *defaultPost) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error) {
	client := pb.NewPostClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

// 更新帖子
func (m *defaultPost) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewPostClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

// 删除帖子
func (m *defaultPost) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewPostClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

// 获取帖子详情
func (m *defaultPost) GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error) {
	client := pb.NewPostClient(m.cli.Conn())
	return client.GetPostDetail(ctx, in, opts...)
}

// 帖子列表
func (m *defaultPost) ListPosts(ctx context.Context, in *ListPostsReq, opts ...grpc.CallOption) (*ListPostsResp, error) {
	client := pb.NewPostClient(m.cli.Conn())
	return client.ListPosts(ctx, in, opts...)
}

// 点赞/取消点赞
func (m *defaultPost) LikePost(ctx context.Context, in *LikePostReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewPostClient(m.cli.Conn())
	return client.LikePost(ctx, in, opts...)
}

// 收藏/取消收藏
func (m *defaultPost) StarPost(ctx context.Context, in *StarPostReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewPostClient(m.cli.Conn())
	return client.StarPost(ctx, in, opts...)
}
