// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: sso.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QrcodeStatusResp_Status int32

const (
	QrcodeStatusResp_WAITING   QrcodeStatusResp_Status = 0 // 等待扫描
	QrcodeStatusResp_SCANNED   QrcodeStatusResp_Status = 1 // 已扫描(手机端已扫描二维码)
	QrcodeStatusResp_CONFIRMED QrcodeStatusResp_Status = 2 // 已确认(手机端已确认登录)
	QrcodeStatusResp_EXPIRED   QrcodeStatusResp_Status = 3 // 已过期
)

// Enum value maps for QrcodeStatusResp_Status.
var (
	QrcodeStatusResp_Status_name = map[int32]string{
		0: "WAITING",
		1: "SCANNED",
		2: "CONFIRMED",
		3: "EXPIRED",
	}
	QrcodeStatusResp_Status_value = map[string]int32{
		"WAITING":   0,
		"SCANNED":   1,
		"CONFIRMED": 2,
		"EXPIRED":   3,
	}
)

func (x QrcodeStatusResp_Status) Enum() *QrcodeStatusResp_Status {
	p := new(QrcodeStatusResp_Status)
	*p = x
	return p
}

func (x QrcodeStatusResp_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QrcodeStatusResp_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_sso_proto_enumTypes[0].Descriptor()
}

func (QrcodeStatusResp_Status) Type() protoreflect.EnumType {
	return &file_sso_proto_enumTypes[0]
}

func (x QrcodeStatusResp_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QrcodeStatusResp_Status.Descriptor instead.
func (QrcodeStatusResp_Status) EnumDescriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{7, 0}
}

// ==============================================登录==============================================
// 登录请求
type LoginByMobileReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"mobile"
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile"` // 手机号(必填，格式校验)
	// @inject_tag: json:"sms_code"
	SmsCode string `protobuf:"bytes,2,opt,name=sms_code,json=smsCode,proto3" json:"sms_code"` // 短信验证码(必填，6位数字)
	// @inject_tag: json:"device_type"
	DeviceType *string `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3,oneof" json:"device_type"` // 设备类型: app/pc/h5(可选)
	// @inject_tag: json:"device_id"
	DeviceId *string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3,oneof" json:"device_id"` // 设备唯一标识(可选)
	// @inject_tag: json:"login_ip"
	LoginIp       *string `protobuf:"bytes,5,opt,name=login_ip,json=loginIp,proto3,oneof" json:"login_ip"` // 登录IP(可选，格式校验)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByMobileReq) Reset() {
	*x = LoginByMobileReq{}
	mi := &file_sso_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByMobileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByMobileReq) ProtoMessage() {}

func (x *LoginByMobileReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByMobileReq.ProtoReflect.Descriptor instead.
func (*LoginByMobileReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{0}
}

func (x *LoginByMobileReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginByMobileReq) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

func (x *LoginByMobileReq) GetDeviceType() string {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return ""
}

func (x *LoginByMobileReq) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *LoginByMobileReq) GetLoginIp() string {
	if x != nil && x.LoginIp != nil {
		return *x.LoginIp
	}
	return ""
}

// 账号密码登录请求
type LoginByPasswordReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"account"
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account"` // 账号
	// @inject_tag: json:"password"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"` // 密码
	// @inject_tag: json:"device_type"
	DeviceType string `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type"` // 设备类型: app/pc/h5
	// @inject_tag: json:"device_id"
	DeviceId string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id"` // 设备唯一标识
	// @inject_tag: json:"login_ip"
	LoginIp string `protobuf:"bytes,5,opt,name=login_ip,json=loginIp,proto3" json:"login_ip"` // 登录IP
	// @inject_tag: json:"agent"
	Agent         string `protobuf:"bytes,6,opt,name=agent,proto3" json:"agent"` // 客户端信息(可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByPasswordReq) Reset() {
	*x = LoginByPasswordReq{}
	mi := &file_sso_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByPasswordReq) ProtoMessage() {}

func (x *LoginByPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByPasswordReq.ProtoReflect.Descriptor instead.
func (*LoginByPasswordReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{1}
}

func (x *LoginByPasswordReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginByPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginByPasswordReq) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *LoginByPasswordReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginByPasswordReq) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *LoginByPasswordReq) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

// 第三方平台登录请求
type LoginByThirdPartyReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"platform"
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform"` // 第三方平台(必填，支持: wechat/qq/alipay)
	// @inject_tag: json:"open_id"
	OpenId string `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id"` // 平台openId(必填)
	// @inject_tag: json:"union_id"
	UnionId *string `protobuf:"bytes,3,opt,name=union_id,json=unionId,proto3,oneof" json:"union_id"` // 跨应用统一标识(如微信UnionID，可选)
	// @inject_tag: json:"device_type"
	DeviceType *string `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3,oneof" json:"device_type"` // 设备类型: app/pc/h5(可选)
	// @inject_tag: json:"device_id"
	DeviceId *string `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3,oneof" json:"device_id"` // 设备唯一标识(可选)
	// @inject_tag: json:"login_ip"
	LoginIp       *string `protobuf:"bytes,6,opt,name=login_ip,json=loginIp,proto3,oneof" json:"login_ip"` // 登录IP(可选，格式校验)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByThirdPartyReq) Reset() {
	*x = LoginByThirdPartyReq{}
	mi := &file_sso_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByThirdPartyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByThirdPartyReq) ProtoMessage() {}

func (x *LoginByThirdPartyReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByThirdPartyReq.ProtoReflect.Descriptor instead.
func (*LoginByThirdPartyReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{2}
}

func (x *LoginByThirdPartyReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LoginByThirdPartyReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *LoginByThirdPartyReq) GetUnionId() string {
	if x != nil && x.UnionId != nil {
		return *x.UnionId
	}
	return ""
}

func (x *LoginByThirdPartyReq) GetDeviceType() string {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return ""
}

func (x *LoginByThirdPartyReq) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *LoginByThirdPartyReq) GetLoginIp() string {
	if x != nil && x.LoginIp != nil {
		return *x.LoginIp
	}
	return ""
}

// 登录响应
type LoginResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"access_token"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token"` // 访问Token
	// @inject_tag: json:"access_token_expire"
	AccessTokenExpire int64 `protobuf:"varint,2,opt,name=access_token_expire,json=accessTokenExpire,proto3" json:"access_token_expire"` // 访问Token过期时间
	// @inject_tag: json:"refresh_token"
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"` // 刷新Token
	// @inject_tag: json:"refresh_token_expire"
	RefreshTokenExpire int64 `protobuf:"varint,4,opt,name=refresh_token_expire,json=refreshTokenExpire,proto3" json:"refresh_token_expire"` // 刷新Token过期时间
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_sso_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResp) GetAccessTokenExpire() int64 {
	if x != nil {
		return x.AccessTokenExpire
	}
	return 0
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetRefreshTokenExpire() int64 {
	if x != nil {
		return x.RefreshTokenExpire
	}
	return 0
}

// ==============================================二维码==============================================
// 二维码生成请求
type QrcodeReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"device_id"
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id"` // 设备唯一标识
	// @inject_tag: json:"login_ip"
	LoginIp       string `protobuf:"bytes,2,opt,name=login_ip,json=loginIp,proto3" json:"login_ip"` // 登录IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrcodeReq) Reset() {
	*x = QrcodeReq{}
	mi := &file_sso_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrcodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrcodeReq) ProtoMessage() {}

func (x *QrcodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrcodeReq.ProtoReflect.Descriptor instead.
func (*QrcodeReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{4}
}

func (x *QrcodeReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *QrcodeReq) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

// 二维码生成响应
type QrcodeResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"qid"
	Qid string `protobuf:"bytes,1,opt,name=qid,proto3" json:"qid"` // 二维码唯一ID
	// @inject_tag: json:"image_url"
	ImageUrl      string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url"` // 二维码图片URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrcodeResp) Reset() {
	*x = QrcodeResp{}
	mi := &file_sso_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrcodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrcodeResp) ProtoMessage() {}

func (x *QrcodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrcodeResp.ProtoReflect.Descriptor instead.
func (*QrcodeResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{5}
}

func (x *QrcodeResp) GetQid() string {
	if x != nil {
		return x.Qid
	}
	return ""
}

func (x *QrcodeResp) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// 二维码状态请求
type QrcodeStatusReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"qid"
	Qid           string `protobuf:"bytes,1,opt,name=qid,proto3" json:"qid"` // 二维码ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrcodeStatusReq) Reset() {
	*x = QrcodeStatusReq{}
	mi := &file_sso_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrcodeStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrcodeStatusReq) ProtoMessage() {}

func (x *QrcodeStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrcodeStatusReq.ProtoReflect.Descriptor instead.
func (*QrcodeStatusReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{6}
}

func (x *QrcodeStatusReq) GetQid() string {
	if x != nil {
		return x.Qid
	}
	return ""
}

// 二维码状态响应
type QrcodeStatusResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"status"
	Status QrcodeStatusResp_Status `protobuf:"varint,1,opt,name=status,proto3,enum=sso.QrcodeStatusResp_Status" json:"status"` // 二维码状态
	// @inject_tag: json:"token"
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token"` // 登录成功的Token(当状态为CONFIRMED时返回)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrcodeStatusResp) Reset() {
	*x = QrcodeStatusResp{}
	mi := &file_sso_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrcodeStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrcodeStatusResp) ProtoMessage() {}

func (x *QrcodeStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrcodeStatusResp.ProtoReflect.Descriptor instead.
func (*QrcodeStatusResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{7}
}

func (x *QrcodeStatusResp) GetStatus() QrcodeStatusResp_Status {
	if x != nil {
		return x.Status
	}
	return QrcodeStatusResp_WAITING
}

func (x *QrcodeStatusResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 二维码确认请求
type QrcodeConfirmReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"qid"
	Qid string `protobuf:"bytes,1,opt,name=qid,proto3" json:"qid"` // 二维码ID
	// @inject_tag: json:"app_token"
	AppToken      string `protobuf:"bytes,2,opt,name=app_token,json=appToken,proto3" json:"app_token"` // 手机端Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrcodeConfirmReq) Reset() {
	*x = QrcodeConfirmReq{}
	mi := &file_sso_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrcodeConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrcodeConfirmReq) ProtoMessage() {}

func (x *QrcodeConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrcodeConfirmReq.ProtoReflect.Descriptor instead.
func (*QrcodeConfirmReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{8}
}

func (x *QrcodeConfirmReq) GetQid() string {
	if x != nil {
		return x.Qid
	}
	return ""
}

func (x *QrcodeConfirmReq) GetAppToken() string {
	if x != nil {
		return x.AppToken
	}
	return ""
}

// ==============================================会话==============================================
// 会话验证请求
type VerifyReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"token"
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token"` // 待验证的Token
	// @inject_tag: json:"device_type"
	DeviceType    string `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type"` // 设备类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyReq) Reset() {
	*x = VerifyReq{}
	mi := &file_sso_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReq) ProtoMessage() {}

func (x *VerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReq.ProtoReflect.Descriptor instead.
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyReq) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

// 会话验证响应
type VerifyResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"` // 用户ID
	// @inject_tag: json:"device_type"
	DeviceType string `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type"` // 设备类型
	// @inject_tag: json:"device_id"
	DeviceId      string `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id"` // 设备ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResp) Reset() {
	*x = VerifyResp{}
	mi := &file_sso_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResp) ProtoMessage() {}

func (x *VerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResp.ProtoReflect.Descriptor instead.
func (*VerifyResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyResp) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *VerifyResp) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// ==============================================登出==============================================
// 登出请求
type LogoutReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"token"
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token"` // 当前Token
	// @inject_tag: json:"device_type"
	DeviceType    string `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type"` // 设备类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_sso_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LogoutReq) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

type LogoutResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"` // 登出结果
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` // 提示信息(如"账号已在其他设备登录")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResp) Reset() {
	*x = LogoutResp{}
	mi := &file_sso_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResp) ProtoMessage() {}

func (x *LogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResp.ProtoReflect.Descriptor instead.
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{12}
}

func (x *LogoutResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ==============================================注册==============================================
type RegisterReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"mobile"
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile"`
	// @inject_tag: json:"password"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	// @inject_tag: json:"sms_code"
	SmsCode string `protobuf:"bytes,3,opt,name=sms_code,json=smsCode,proto3" json:"sms_code"`
	// @inject_tag: json:"account"
	Account       string `protobuf:"bytes,4,opt,name=account,proto3" json:"account"` // 账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_sso_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

func (x *RegisterReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// 注册响应（与登录响应结构一致，便于客户端统一处理）
type RegisterResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"token"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"token"` // 新访问Token
	// @inject_tag: json:"access_token_expire"
	AccessTokenExpire int64 `protobuf:"varint,2,opt,name=access_token_expire,json=accessTokenExpire,proto3" json:"access_token_expire"` // 新访问Token有效期(秒)
	// @inject_tag: json:"refresh_token"
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"` // 新刷新Token(延长有效期)
	// @inject_tag: json:"refresh_token_expire"
	RefreshTokenExpire int64 `protobuf:"varint,4,opt,name=refresh_token_expire,json=refreshTokenExpire,proto3" json:"refresh_token_expire"` // 新刷新Token有效期(秒)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_sso_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResp) GetAccessTokenExpire() int64 {
	if x != nil {
		return x.AccessTokenExpire
	}
	return 0
}

func (x *RegisterResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RegisterResp) GetRefreshTokenExpire() int64 {
	if x != nil {
		return x.RefreshTokenExpire
	}
	return 0
}

// ==============================================验证码==============================================
// 短信验证码请求
type SendSmsCodeReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"mobile"
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile"` // 手机号(必填)
	// @inject_tag: json:"scene"
	Scene         string `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene"` // 场景: register/login/reset_pwd
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsCodeReq) Reset() {
	*x = SendSmsCodeReq{}
	mi := &file_sso_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeReq) ProtoMessage() {}

func (x *SendSmsCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeReq.ProtoReflect.Descriptor instead.
func (*SendSmsCodeReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{15}
}

func (x *SendSmsCodeReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SendSmsCodeReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

// 短信验证码响应
type SendSmsCodeResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// @inject_tag: json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	// @inject_tag: json:"expire_seconds"
	ExpireSeconds int32 `protobuf:"varint,3,opt,name=expire_seconds,json=expireSeconds,proto3" json:"expire_seconds"` // 验证码有效期(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsCodeResp) Reset() {
	*x = SendSmsCodeResp{}
	mi := &file_sso_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeResp) ProtoMessage() {}

func (x *SendSmsCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeResp.ProtoReflect.Descriptor instead.
func (*SendSmsCodeResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{16}
}

func (x *SendSmsCodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendSmsCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendSmsCodeResp) GetExpireSeconds() int32 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

// 邮箱验证码请求(同短信验证码结构)
type SendEmailCodeReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email"` // 邮箱(必填)
	// @inject_tag: json:"scene"
	Scene         string `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene"` // 场景
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailCodeReq) Reset() {
	*x = SendEmailCodeReq{}
	mi := &file_sso_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailCodeReq) ProtoMessage() {}

func (x *SendEmailCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailCodeReq.ProtoReflect.Descriptor instead.
func (*SendEmailCodeReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{17}
}

func (x *SendEmailCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendEmailCodeReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

// 邮箱验证码响应(同短信)
type SendEmailCodeResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// @inject_tag: json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	// @inject_tag: json:"expire_seconds"
	ExpireSeconds int32 `protobuf:"varint,3,opt,name=expire_seconds,json=expireSeconds,proto3" json:"expire_seconds"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailCodeResp) Reset() {
	*x = SendEmailCodeResp{}
	mi := &file_sso_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailCodeResp) ProtoMessage() {}

func (x *SendEmailCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailCodeResp.ProtoReflect.Descriptor instead.
func (*SendEmailCodeResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{18}
}

func (x *SendEmailCodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendEmailCodeResp) GetExpireSeconds() int32 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

// ==============================================重置密码==============================================
// 密码重置请求(手机号)
type ResetPasswordReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"mobile"
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile"` // 手机号(必填)
	// @inject_tag: json:"sms_code"
	SmsCode string `protobuf:"bytes,2,opt,name=sms_code,json=smsCode,proto3" json:"sms_code"` // 短信验证码(必填)
	// @inject_tag: json:"new_password"
	NewPassword   string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password"` // 新密码(必填，8-32位字母/数字/特殊字符)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReq) Reset() {
	*x = ResetPasswordReq{}
	mi := &file_sso_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReq) ProtoMessage() {}

func (x *ResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{19}
}

func (x *ResetPasswordReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ResetPasswordReq) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

func (x *ResetPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// 邮箱重置密码请求
type ResetPasswordByEmailReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email"` // 邮箱(必填)
	// @inject_tag: json:"email_code"
	EmailCode string `protobuf:"bytes,2,opt,name=email_code,json=emailCode,proto3" json:"email_code"` // 邮箱验证码(必填)
	// @inject_tag: json:"new_password"
	NewPassword   string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password"` // 新密码(同手机号重置规则)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordByEmailReq) Reset() {
	*x = ResetPasswordByEmailReq{}
	mi := &file_sso_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordByEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordByEmailReq) ProtoMessage() {}

func (x *ResetPasswordByEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordByEmailReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordByEmailReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{20}
}

func (x *ResetPasswordByEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordByEmailReq) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

func (x *ResetPasswordByEmailReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// 密码重置响应(通用)
type ResetPasswordResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResp) Reset() {
	*x = ResetPasswordResp{}
	mi := &file_sso_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResp) ProtoMessage() {}

func (x *ResetPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResp.ProtoReflect.Descriptor instead.
func (*ResetPasswordResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{21}
}

func (x *ResetPasswordResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetPasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetPasswordByEmailResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"` // 与ResetPasswordResp结构一致，便于复用
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordByEmailResp) Reset() {
	*x = ResetPasswordByEmailResp{}
	mi := &file_sso_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordByEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordByEmailResp) ProtoMessage() {}

func (x *ResetPasswordByEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordByEmailResp.ProtoReflect.Descriptor instead.
func (*ResetPasswordByEmailResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{22}
}

func (x *ResetPasswordByEmailResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetPasswordByEmailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ==============================================刷新Token==============================================
// 刷新Token请求
type RefreshTokenReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"refresh_token"
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"` // 刷新Token(必填)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_sso_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{23}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 刷新Token响应
type RefreshTokenResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"token"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"token"` // 新访问Token
	// @inject_tag: json:"access_token_expire"
	AccessTokenExpire int64 `protobuf:"varint,2,opt,name=access_token_expire,json=accessTokenExpire,proto3" json:"access_token_expire"` // 新访问Token有效期(秒)
	// @inject_tag: json:"refresh_token"
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"` // 新刷新Token(延长有效期)
	// @inject_tag: json:"refresh_token_expire"
	RefreshTokenExpire int64 `protobuf:"varint,4,opt,name=refresh_token_expire,json=refreshTokenExpire,proto3" json:"refresh_token_expire"` // 新刷新Token有效期(秒)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	mi := &file_sso_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{24}
}

func (x *RefreshTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResp) GetAccessTokenExpire() int64 {
	if x != nil {
		return x.AccessTokenExpire
	}
	return 0
}

func (x *RefreshTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResp) GetRefreshTokenExpire() int64 {
	if x != nil {
		return x.RefreshTokenExpire
	}
	return 0
}

// ==============================================绑定==============================================
// 绑定手机号请求
type BindMobileReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"mobile"
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile"` // 手机号(必填)
	// @inject_tag: json:"sms_code"
	SmsCode       string `protobuf:"bytes,2,opt,name=sms_code,json=smsCode,proto3" json:"sms_code"` // 验证码(必填)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindMobileReq) Reset() {
	*x = BindMobileReq{}
	mi := &file_sso_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMobileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMobileReq) ProtoMessage() {}

func (x *BindMobileReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMobileReq.ProtoReflect.Descriptor instead.
func (*BindMobileReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{25}
}

func (x *BindMobileReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *BindMobileReq) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

// 绑定邮箱请求
type BindEmailReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email"` // 邮箱(必填)
	// @inject_tag: json:"email_code"
	EmailCode     string `protobuf:"bytes,2,opt,name=email_code,json=emailCode,proto3" json:"email_code"` // 验证码(必填)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindEmailReq) Reset() {
	*x = BindEmailReq{}
	mi := &file_sso_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEmailReq) ProtoMessage() {}

func (x *BindEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEmailReq.ProtoReflect.Descriptor instead.
func (*BindEmailReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{26}
}

func (x *BindEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BindEmailReq) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

// 第三方平台绑定请求
type BindThirdPartyReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"platform"
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform"` // 平台(必填)
	// @inject_tag: json:"open_id"
	OpenId string `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id"` // OpenID(必填)
	// @inject_tag: json:"union_id"
	UnionId       string `protobuf:"bytes,3,opt,name=union_id,json=unionId,proto3" json:"union_id"` // 可选，跨应用统一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindThirdPartyReq) Reset() {
	*x = BindThirdPartyReq{}
	mi := &file_sso_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindThirdPartyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindThirdPartyReq) ProtoMessage() {}

func (x *BindThirdPartyReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindThirdPartyReq.ProtoReflect.Descriptor instead.
func (*BindThirdPartyReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{27}
}

func (x *BindThirdPartyReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *BindThirdPartyReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *BindThirdPartyReq) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

// 绑定/解绑响应(通用结构)
type BindMobileResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"` // 绑定结果
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` // 提示信息(如"绑定成功"或"手机号已绑定")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindMobileResp) Reset() {
	*x = BindMobileResp{}
	mi := &file_sso_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMobileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMobileResp) ProtoMessage() {}

func (x *BindMobileResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMobileResp.ProtoReflect.Descriptor instead.
func (*BindMobileResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{28}
}

func (x *BindMobileResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindMobileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BindEmailResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"` // 绑定结果
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` // 提示信息(如"绑定成功"或"邮箱已绑定")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindEmailResp) Reset() {
	*x = BindEmailResp{}
	mi := &file_sso_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEmailResp) ProtoMessage() {}

func (x *BindEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEmailResp.ProtoReflect.Descriptor instead.
func (*BindEmailResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{29}
}

func (x *BindEmailResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindEmailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BindThirdPartyResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"` // 绑定结果
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` // 提示信息(如"绑定成功"或"第三方平台已绑定")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindThirdPartyResp) Reset() {
	*x = BindThirdPartyResp{}
	mi := &file_sso_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindThirdPartyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindThirdPartyResp) ProtoMessage() {}

func (x *BindThirdPartyResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindThirdPartyResp.ProtoReflect.Descriptor instead.
func (*BindThirdPartyResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{30}
}

func (x *BindThirdPartyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindThirdPartyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ==============================================解绑==============================================
// 解绑手机号请求（需验证验证码防止误操作）
type UnbindMobileReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"mobile"
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile"` // 待解绑手机号(必填)
	// @inject_tag: json:"sms_code"
	SmsCode       string `protobuf:"bytes,2,opt,name=sms_code,json=smsCode,proto3" json:"sms_code"` // 短信验证码(必填，验证手机号归属)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindMobileReq) Reset() {
	*x = UnbindMobileReq{}
	mi := &file_sso_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindMobileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindMobileReq) ProtoMessage() {}

func (x *UnbindMobileReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindMobileReq.ProtoReflect.Descriptor instead.
func (*UnbindMobileReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{31}
}

func (x *UnbindMobileReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UnbindMobileReq) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

// 解绑邮箱请求（需验证验证码）
type UnbindEmailReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email"` // 待解绑邮箱(必填)
	// @inject_tag: json:"email_code"
	EmailCode     string `protobuf:"bytes,2,opt,name=email_code,json=emailCode,proto3" json:"email_code"` // 邮箱验证码(必填，验证邮箱归属)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindEmailReq) Reset() {
	*x = UnbindEmailReq{}
	mi := &file_sso_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindEmailReq) ProtoMessage() {}

func (x *UnbindEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindEmailReq.ProtoReflect.Descriptor instead.
func (*UnbindEmailReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{32}
}

func (x *UnbindEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UnbindEmailReq) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

// 解绑第三方平台请求
type UnbindThirdPartyReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"platform"
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform"` // 平台(必填，限制可选值)
	// @inject_tag: json:"open_id"
	OpenId string `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id"` // 平台唯一标识(必填)
	// @inject_tag: json:"union_id"
	UnionId       string `protobuf:"bytes,3,opt,name=union_id,json=unionId,proto3" json:"union_id"` // 可选，跨应用统一标识(如微信UnionID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindThirdPartyReq) Reset() {
	*x = UnbindThirdPartyReq{}
	mi := &file_sso_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindThirdPartyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindThirdPartyReq) ProtoMessage() {}

func (x *UnbindThirdPartyReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindThirdPartyReq.ProtoReflect.Descriptor instead.
func (*UnbindThirdPartyReq) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{33}
}

func (x *UnbindThirdPartyReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UnbindThirdPartyReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UnbindThirdPartyReq) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

type UnbindMobileResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"` // 解绑结果
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` // 提示信息(如"解绑成功"或"手机号未绑定")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindMobileResp) Reset() {
	*x = UnbindMobileResp{}
	mi := &file_sso_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindMobileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindMobileResp) ProtoMessage() {}

func (x *UnbindMobileResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindMobileResp.ProtoReflect.Descriptor instead.
func (*UnbindMobileResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{34}
}

func (x *UnbindMobileResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnbindMobileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnbindEmailResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"` // 解绑结果
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` // 提示信息(如"解绑成功"或"邮箱未绑定")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindEmailResp) Reset() {
	*x = UnbindEmailResp{}
	mi := &file_sso_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindEmailResp) ProtoMessage() {}

func (x *UnbindEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindEmailResp.ProtoReflect.Descriptor instead.
func (*UnbindEmailResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{35}
}

func (x *UnbindEmailResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnbindEmailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnbindThirdPartyResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"success"
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"` // 解绑结果
	// @inject_tag: json:"message"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` // 提示信息(如"解绑成功"或"第三方平台未绑定")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindThirdPartyResp) Reset() {
	*x = UnbindThirdPartyResp{}
	mi := &file_sso_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindThirdPartyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindThirdPartyResp) ProtoMessage() {}

func (x *UnbindThirdPartyResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindThirdPartyResp.ProtoReflect.Descriptor instead.
func (*UnbindThirdPartyResp) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{36}
}

func (x *UnbindThirdPartyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnbindThirdPartyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_sso_proto protoreflect.FileDescriptor

const file_sso_proto_rawDesc = "" +
	"\n" +
	"\tsso.proto\x12\x03sso\x1a\x17validate/validate.proto\"\x9e\x02\n" +
	"\x10LoginByMobileReq\x12H\n" +
	"\x06mobile\x18\x01 \x01(\tB0\xfaB\x14r\x122\r^1[3-9]\\d{9}$\x98\x01\v\x82\xb5\x18\x15手机号格式错误R\x06mobile\x12$\n" +
	"\bsms_code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\x06R\asmsCode\x12$\n" +
	"\vdevice_type\x18\x03 \x01(\tH\x00R\n" +
	"deviceType\x88\x01\x01\x12 \n" +
	"\tdevice_id\x18\x04 \x01(\tH\x01R\bdeviceId\x88\x01\x01\x12'\n" +
	"\blogin_ip\x18\x05 \x01(\tB\a\xfaB\x04r\x02x\x01H\x02R\aloginIp\x88\x01\x01B\x0e\n" +
	"\f_device_typeB\f\n" +
	"\n" +
	"_device_idB\v\n" +
	"\t_login_ip\"\xd8\x01\n" +
	"\x12LoginByPasswordReq\x12#\n" +
	"\aaccount\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\x14R\aaccount\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18 R\bpassword\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\"\n" +
	"\blogin_ip\x18\x05 \x01(\tB\a\xfaB\x04r\x02x\x01R\aloginIp\x12\x14\n" +
	"\x05agent\x18\x06 \x01(\tR\x05agent\"\xb8\x02\n" +
	"\x14LoginByThirdPartyReq\x125\n" +
	"\bplatform\x18\x01 \x01(\tB\x19\xfaB\x16r\x14R\x06wechatR\x02qqR\x06alipayR\bplatform\x12 \n" +
	"\aopen_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\n" +
	"R\x06openId\x12\x1e\n" +
	"\bunion_id\x18\x03 \x01(\tH\x00R\aunionId\x88\x01\x01\x12$\n" +
	"\vdevice_type\x18\x04 \x01(\tH\x01R\n" +
	"deviceType\x88\x01\x01\x12 \n" +
	"\tdevice_id\x18\x05 \x01(\tH\x02R\bdeviceId\x88\x01\x01\x12'\n" +
	"\blogin_ip\x18\x06 \x01(\tB\a\xfaB\x04r\x02x\x01H\x03R\aloginIp\x88\x01\x01B\v\n" +
	"\t_union_idB\x0e\n" +
	"\f_device_typeB\f\n" +
	"\n" +
	"_device_idB\v\n" +
	"\t_login_ip\"\xb5\x01\n" +
	"\tLoginResp\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12.\n" +
	"\x13access_token_expire\x18\x02 \x01(\x03R\x11accessTokenExpire\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x120\n" +
	"\x14refresh_token_expire\x18\x04 \x01(\x03R\x12refreshTokenExpire\"C\n" +
	"\tQrcodeReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x19\n" +
	"\blogin_ip\x18\x02 \x01(\tR\aloginIp\";\n" +
	"\n" +
	"QrcodeResp\x12\x10\n" +
	"\x03qid\x18\x01 \x01(\tR\x03qid\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\"#\n" +
	"\x0fQrcodeStatusReq\x12\x10\n" +
	"\x03qid\x18\x01 \x01(\tR\x03qid\"\x9e\x01\n" +
	"\x10QrcodeStatusResp\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.sso.QrcodeStatusResp.StatusR\x06status\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\">\n" +
	"\x06Status\x12\v\n" +
	"\aWAITING\x10\x00\x12\v\n" +
	"\aSCANNED\x10\x01\x12\r\n" +
	"\tCONFIRMED\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x03\"A\n" +
	"\x10QrcodeConfirmReq\x12\x10\n" +
	"\x03qid\x18\x01 \x01(\tR\x03qid\x12\x1b\n" +
	"\tapp_token\x18\x02 \x01(\tR\bappToken\"B\n" +
	"\tVerifyReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x01(\tR\n" +
	"deviceType\"c\n" +
	"\n" +
	"VerifyResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x01(\tR\n" +
	"deviceType\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"B\n" +
	"\tLogoutReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x01(\tR\n" +
	"deviceType\"@\n" +
	"\n" +
	"LogoutResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xae\x02\n" +
	"\vRegisterReq\x12H\n" +
	"\x06mobile\x18\x01 \x01(\tB0\xfaB\x14r\x122\r^1[3-9]\\d{9}$\x98\x01\v\x82\xb5\x18\x15手机号格式错误R\x06mobile\x12K\n" +
	"\bpassword\x18\x02 \x01(\tB/\xfaB\x06r\x04\x10\b\x18 \x82\xb5\x18\"密码长度必须在8-32位之间R\bpassword\x12=\n" +
	"\bsms_code\x18\x03 \x01(\tB\"\xfaB\x06r\x04\x10\x04\x18\x06\x82\xb5\x18\x15验证码格式错误R\asmsCode\x12I\n" +
	"\aaccount\x18\x04 \x01(\tB/\xfaB\x16r\x14\x10\x04\x18\x102\x0e^[a-zA-Z0-9]+$\x82\xb5\x18\x12账号格式错误R\aaccount\"\xb8\x01\n" +
	"\fRegisterResp\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12.\n" +
	"\x13access_token_expire\x18\x02 \x01(\x03R\x11accessTokenExpire\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x120\n" +
	"\x14refresh_token_expire\x18\x04 \x01(\x03R\x12refreshTokenExpire\"\x93\x01\n" +
	"\x0eSendSmsCodeReq\x12H\n" +
	"\x06mobile\x18\x01 \x01(\tB0\xfaB\x14r\x122\r^1[3-9]\\d{9}$\x98\x01\v\x82\xb5\x18\x15手机号格式错误R\x06mobile\x127\n" +
	"\x05scene\x18\x02 \x01(\tB!\xfaB\x1er\x1cR\bregisterR\x05loginR\treset_pwdR\x05scene\"l\n" +
	"\x0fSendSmsCodeResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eexpire_seconds\x18\x03 \x01(\x05R\rexpireSeconds\"x\n" +
	"\x10SendEmailCodeReq\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12E\n" +
	"\x05scene\x18\x02 \x01(\tB/\xfaB,r*R\bregisterR\x05loginR\treset_pwdR\x04bindR\x06unbindR\x05scene\"n\n" +
	"\x11SendEmailCodeResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eexpire_seconds\x18\x03 \x01(\x05R\rexpireSeconds\"\xb0\x01\n" +
	"\x10ResetPasswordReq\x12H\n" +
	"\x06mobile\x18\x01 \x01(\tB0\xfaB\x14r\x122\r^1[3-9]\\d{9}$\x98\x01\v\x82\xb5\x18\x15手机号格式错误R\x06mobile\x12$\n" +
	"\bsms_code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\x06R\asmsCode\x12,\n" +
	"\fnew_password\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18 R\vnewPassword\"\x90\x01\n" +
	"\x17ResetPasswordByEmailReq\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12(\n" +
	"\n" +
	"email_code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\x06R\temailCode\x12,\n" +
	"\fnew_password\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18 R\vnewPassword\"G\n" +
	"\x11ResetPasswordResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x18ResetPasswordByEmailResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x0fRefreshTokenReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xbc\x01\n" +
	"\x10RefreshTokenResp\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12.\n" +
	"\x13access_token_expire\x18\x02 \x01(\x03R\x11accessTokenExpire\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x120\n" +
	"\x14refresh_token_expire\x18\x04 \x01(\x03R\x12refreshTokenExpire\"\x7f\n" +
	"\rBindMobileReq\x12H\n" +
	"\x06mobile\x18\x01 \x01(\tB0\xfaB\x14r\x122\r^1[3-9]\\d{9}$\x98\x01\v\x82\xb5\x18\x15手机号格式错误R\x06mobile\x12$\n" +
	"\bsms_code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\x06R\asmsCode\"W\n" +
	"\fBindEmailReq\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12(\n" +
	"\n" +
	"email_code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\x06R\temailCode\"\x87\x01\n" +
	"\x11BindThirdPartyReq\x125\n" +
	"\bplatform\x18\x01 \x01(\tB\x19\xfaB\x16r\x14R\x06wechatR\x02qqR\x06alipayR\bplatform\x12 \n" +
	"\aopen_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\n" +
	"R\x06openId\x12\x19\n" +
	"\bunion_id\x18\x03 \x01(\tR\aunionId\"D\n" +
	"\x0eBindMobileResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\rBindEmailResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x12BindThirdPartyResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x01\n" +
	"\x0fUnbindMobileReq\x12H\n" +
	"\x06mobile\x18\x01 \x01(\tB0\xfaB\x14r\x122\r^1[3-9]\\d{9}$\x98\x01\v\x82\xb5\x18\x15手机号格式错误R\x06mobile\x12$\n" +
	"\bsms_code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\x06R\asmsCode\"Y\n" +
	"\x0eUnbindEmailReq\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12(\n" +
	"\n" +
	"email_code\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18\x06R\temailCode\"\x89\x01\n" +
	"\x13UnbindThirdPartyReq\x125\n" +
	"\bplatform\x18\x01 \x01(\tB\x19\xfaB\x16r\x14R\x06wechatR\x02qqR\x06alipayR\bplatform\x12 \n" +
	"\aopen_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\n" +
	"R\x06openId\x12\x19\n" +
	"\bunion_id\x18\x03 \x01(\tR\aunionId\"F\n" +
	"\x10UnbindMobileResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x0fUnbindEmailResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x14UnbindThirdPartyResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb2\t\n" +
	"\x04auth\x126\n" +
	"\rLoginByMobile\x12\x15.sso.LoginByMobileReq\x1a\x0e.sso.LoginResp\x12:\n" +
	"\x0fLoginByPassword\x12\x17.sso.LoginByPasswordReq\x1a\x0e.sso.LoginResp\x12>\n" +
	"\x11LoginByThirdParty\x12\x19.sso.LoginByThirdPartyReq\x1a\x0e.sso.LoginResp\x121\n" +
	"\x0eGenerateQrcode\x12\x0e.sso.QrcodeReq\x1a\x0f.sso.QrcodeResp\x12@\n" +
	"\x11CheckQrcodeStatus\x12\x14.sso.QrcodeStatusReq\x1a\x15.sso.QrcodeStatusResp\x12;\n" +
	"\x12ConfirmQrcodeLogin\x12\x15.sso.QrcodeConfirmReq\x1a\x0e.sso.LoginResp\x12.\n" +
	"\vVerifyToken\x12\x0e.sso.VerifyReq\x1a\x0f.sso.VerifyResp\x12)\n" +
	"\x06Logout\x12\x0e.sso.LogoutReq\x1a\x0f.sso.LogoutResp\x12/\n" +
	"\bRegister\x12\x10.sso.RegisterReq\x1a\x11.sso.RegisterResp\x128\n" +
	"\vSendSmsCode\x12\x13.sso.SendSmsCodeReq\x1a\x14.sso.SendSmsCodeResp\x12>\n" +
	"\rResetPassword\x12\x15.sso.ResetPasswordReq\x1a\x16.sso.ResetPasswordResp\x12;\n" +
	"\fRefreshToken\x12\x14.sso.RefreshTokenReq\x1a\x15.sso.RefreshTokenResp\x12>\n" +
	"\rSendEmailCode\x12\x15.sso.SendEmailCodeReq\x1a\x16.sso.SendEmailCodeResp\x12S\n" +
	"\x14ResetPasswordByEmail\x12\x1c.sso.ResetPasswordByEmailReq\x1a\x1d.sso.ResetPasswordByEmailResp\x125\n" +
	"\n" +
	"BindMobile\x12\x12.sso.BindMobileReq\x1a\x13.sso.BindMobileResp\x122\n" +
	"\tBindEmail\x12\x11.sso.BindEmailReq\x1a\x12.sso.BindEmailResp\x12;\n" +
	"\fUnbindMobile\x12\x14.sso.UnbindMobileReq\x1a\x15.sso.UnbindMobileResp\x128\n" +
	"\vUnbindEmail\x12\x13.sso.UnbindEmailReq\x1a\x14.sso.UnbindEmailResp\x12G\n" +
	"\x10UnbindThirdParty\x12\x18.sso.UnbindThirdPartyReq\x1a\x19.sso.UnbindThirdPartyResp\x12A\n" +
	"\x0eBindThirdParty\x12\x16.sso.BindThirdPartyReq\x1a\x17.sso.BindThirdPartyRespB\x06Z\x04./pbb\x06proto3"

var (
	file_sso_proto_rawDescOnce sync.Once
	file_sso_proto_rawDescData []byte
)

func file_sso_proto_rawDescGZIP() []byte {
	file_sso_proto_rawDescOnce.Do(func() {
		file_sso_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_proto_rawDesc), len(file_sso_proto_rawDesc)))
	})
	return file_sso_proto_rawDescData
}

var file_sso_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sso_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_sso_proto_goTypes = []any{
	(QrcodeStatusResp_Status)(0),     // 0: sso.QrcodeStatusResp.Status
	(*LoginByMobileReq)(nil),         // 1: sso.LoginByMobileReq
	(*LoginByPasswordReq)(nil),       // 2: sso.LoginByPasswordReq
	(*LoginByThirdPartyReq)(nil),     // 3: sso.LoginByThirdPartyReq
	(*LoginResp)(nil),                // 4: sso.LoginResp
	(*QrcodeReq)(nil),                // 5: sso.QrcodeReq
	(*QrcodeResp)(nil),               // 6: sso.QrcodeResp
	(*QrcodeStatusReq)(nil),          // 7: sso.QrcodeStatusReq
	(*QrcodeStatusResp)(nil),         // 8: sso.QrcodeStatusResp
	(*QrcodeConfirmReq)(nil),         // 9: sso.QrcodeConfirmReq
	(*VerifyReq)(nil),                // 10: sso.VerifyReq
	(*VerifyResp)(nil),               // 11: sso.VerifyResp
	(*LogoutReq)(nil),                // 12: sso.LogoutReq
	(*LogoutResp)(nil),               // 13: sso.LogoutResp
	(*RegisterReq)(nil),              // 14: sso.RegisterReq
	(*RegisterResp)(nil),             // 15: sso.RegisterResp
	(*SendSmsCodeReq)(nil),           // 16: sso.SendSmsCodeReq
	(*SendSmsCodeResp)(nil),          // 17: sso.SendSmsCodeResp
	(*SendEmailCodeReq)(nil),         // 18: sso.SendEmailCodeReq
	(*SendEmailCodeResp)(nil),        // 19: sso.SendEmailCodeResp
	(*ResetPasswordReq)(nil),         // 20: sso.ResetPasswordReq
	(*ResetPasswordByEmailReq)(nil),  // 21: sso.ResetPasswordByEmailReq
	(*ResetPasswordResp)(nil),        // 22: sso.ResetPasswordResp
	(*ResetPasswordByEmailResp)(nil), // 23: sso.ResetPasswordByEmailResp
	(*RefreshTokenReq)(nil),          // 24: sso.RefreshTokenReq
	(*RefreshTokenResp)(nil),         // 25: sso.RefreshTokenResp
	(*BindMobileReq)(nil),            // 26: sso.BindMobileReq
	(*BindEmailReq)(nil),             // 27: sso.BindEmailReq
	(*BindThirdPartyReq)(nil),        // 28: sso.BindThirdPartyReq
	(*BindMobileResp)(nil),           // 29: sso.BindMobileResp
	(*BindEmailResp)(nil),            // 30: sso.BindEmailResp
	(*BindThirdPartyResp)(nil),       // 31: sso.BindThirdPartyResp
	(*UnbindMobileReq)(nil),          // 32: sso.UnbindMobileReq
	(*UnbindEmailReq)(nil),           // 33: sso.UnbindEmailReq
	(*UnbindThirdPartyReq)(nil),      // 34: sso.UnbindThirdPartyReq
	(*UnbindMobileResp)(nil),         // 35: sso.UnbindMobileResp
	(*UnbindEmailResp)(nil),          // 36: sso.UnbindEmailResp
	(*UnbindThirdPartyResp)(nil),     // 37: sso.UnbindThirdPartyResp
}
var file_sso_proto_depIdxs = []int32{
	0,  // 0: sso.QrcodeStatusResp.status:type_name -> sso.QrcodeStatusResp.Status
	1,  // 1: sso.auth.LoginByMobile:input_type -> sso.LoginByMobileReq
	2,  // 2: sso.auth.LoginByPassword:input_type -> sso.LoginByPasswordReq
	3,  // 3: sso.auth.LoginByThirdParty:input_type -> sso.LoginByThirdPartyReq
	5,  // 4: sso.auth.GenerateQrcode:input_type -> sso.QrcodeReq
	7,  // 5: sso.auth.CheckQrcodeStatus:input_type -> sso.QrcodeStatusReq
	9,  // 6: sso.auth.ConfirmQrcodeLogin:input_type -> sso.QrcodeConfirmReq
	10, // 7: sso.auth.VerifyToken:input_type -> sso.VerifyReq
	12, // 8: sso.auth.Logout:input_type -> sso.LogoutReq
	14, // 9: sso.auth.Register:input_type -> sso.RegisterReq
	16, // 10: sso.auth.SendSmsCode:input_type -> sso.SendSmsCodeReq
	20, // 11: sso.auth.ResetPassword:input_type -> sso.ResetPasswordReq
	24, // 12: sso.auth.RefreshToken:input_type -> sso.RefreshTokenReq
	18, // 13: sso.auth.SendEmailCode:input_type -> sso.SendEmailCodeReq
	21, // 14: sso.auth.ResetPasswordByEmail:input_type -> sso.ResetPasswordByEmailReq
	26, // 15: sso.auth.BindMobile:input_type -> sso.BindMobileReq
	27, // 16: sso.auth.BindEmail:input_type -> sso.BindEmailReq
	32, // 17: sso.auth.UnbindMobile:input_type -> sso.UnbindMobileReq
	33, // 18: sso.auth.UnbindEmail:input_type -> sso.UnbindEmailReq
	34, // 19: sso.auth.UnbindThirdParty:input_type -> sso.UnbindThirdPartyReq
	28, // 20: sso.auth.BindThirdParty:input_type -> sso.BindThirdPartyReq
	4,  // 21: sso.auth.LoginByMobile:output_type -> sso.LoginResp
	4,  // 22: sso.auth.LoginByPassword:output_type -> sso.LoginResp
	4,  // 23: sso.auth.LoginByThirdParty:output_type -> sso.LoginResp
	6,  // 24: sso.auth.GenerateQrcode:output_type -> sso.QrcodeResp
	8,  // 25: sso.auth.CheckQrcodeStatus:output_type -> sso.QrcodeStatusResp
	4,  // 26: sso.auth.ConfirmQrcodeLogin:output_type -> sso.LoginResp
	11, // 27: sso.auth.VerifyToken:output_type -> sso.VerifyResp
	13, // 28: sso.auth.Logout:output_type -> sso.LogoutResp
	15, // 29: sso.auth.Register:output_type -> sso.RegisterResp
	17, // 30: sso.auth.SendSmsCode:output_type -> sso.SendSmsCodeResp
	22, // 31: sso.auth.ResetPassword:output_type -> sso.ResetPasswordResp
	25, // 32: sso.auth.RefreshToken:output_type -> sso.RefreshTokenResp
	19, // 33: sso.auth.SendEmailCode:output_type -> sso.SendEmailCodeResp
	23, // 34: sso.auth.ResetPasswordByEmail:output_type -> sso.ResetPasswordByEmailResp
	29, // 35: sso.auth.BindMobile:output_type -> sso.BindMobileResp
	30, // 36: sso.auth.BindEmail:output_type -> sso.BindEmailResp
	35, // 37: sso.auth.UnbindMobile:output_type -> sso.UnbindMobileResp
	36, // 38: sso.auth.UnbindEmail:output_type -> sso.UnbindEmailResp
	37, // 39: sso.auth.UnbindThirdParty:output_type -> sso.UnbindThirdPartyResp
	31, // 40: sso.auth.BindThirdParty:output_type -> sso.BindThirdPartyResp
	21, // [21:41] is the sub-list for method output_type
	1,  // [1:21] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_sso_proto_init() }
func file_sso_proto_init() {
	if File_sso_proto != nil {
		return
	}
	file_sso_proto_msgTypes[0].OneofWrappers = []any{}
	file_sso_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_proto_rawDesc), len(file_sso_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_proto_goTypes,
		DependencyIndexes: file_sso_proto_depIdxs,
		EnumInfos:         file_sso_proto_enumTypes,
		MessageInfos:      file_sso_proto_msgTypes,
	}.Build()
	File_sso_proto = out.File
	file_sso_proto_goTypes = nil
	file_sso_proto_depIdxs = nil
}
