// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: article.proto

package comment

import (
	"context"

	"github.com/krace-tx/emo_trash/app/rpc/article/article"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticleInfo                      = article.ArticleInfo
	ArticlePopularity                = article.ArticlePopularity
	CheckIfUserActionArticleRequest  = article.CheckIfUserActionArticleRequest
	CheckIfUserActionArticleResponse = article.CheckIfUserActionArticleResponse
	CheckIfUserLikedCommentRequest   = article.CheckIfUserLikedCommentRequest
	CheckIfUserLikedCommentResponse  = article.CheckIfUserLikedCommentResponse
	CommentInfo                      = article.CommentInfo
	CreateArticleRequest             = article.CreateArticleRequest
	CreateArticleResponse            = article.CreateArticleResponse
	CreateCommentRequest             = article.CreateCommentRequest
	CreateCommentResponse            = article.CreateCommentResponse
	DeleteArticleRequest             = article.DeleteArticleRequest
	DeleteArticleResponse            = article.DeleteArticleResponse
	EditArticleRequest               = article.EditArticleRequest
	EditArticleResponse              = article.EditArticleResponse
	GetArticleRequest                = article.GetArticleRequest
	GetArticleResponse               = article.GetArticleResponse
	GetArticleStatsRequest           = article.GetArticleStatsRequest
	GetArticleStatsResponse          = article.GetArticleStatsResponse
	GetArticlesByUserRequest         = article.GetArticlesByUserRequest
	GetArticlesByUserResponse        = article.GetArticlesByUserResponse
	GetCommentLeafCountRequest       = article.GetCommentLeafCountRequest
	GetCommentLeafCountResponse      = article.GetCommentLeafCountResponse
	GetCommentListRequest            = article.GetCommentListRequest
	GetCommentListResponse           = article.GetCommentListResponse
	GetDraftArticlesRequest          = article.GetDraftArticlesRequest
	GetDraftArticlesResponse         = article.GetDraftArticlesResponse
	GetHotTopicsRequest              = article.GetHotTopicsRequest
	GetHotTopicsResponse             = article.GetHotTopicsResponse
	GetLikeCommentCountRequest       = article.GetLikeCommentCountRequest
	GetLikeCommentCountResponse      = article.GetLikeCommentCountResponse
	GetPartitionsRequest             = article.GetPartitionsRequest
	GetPartitionsResponse            = article.GetPartitionsResponse
	GetReplyCommentRequest           = article.GetReplyCommentRequest
	GetReplyCommentResponse          = article.GetReplyCommentResponse
	GlobalSearchRequest              = article.GlobalSearchRequest
	GlobalSearchResponse             = article.GlobalSearchResponse
	LikeCommentRequest               = article.LikeCommentRequest
	LikeCommentResponse              = article.LikeCommentResponse
	Partition                        = article.Partition
	QueryApprovedArticlesRequest     = article.QueryApprovedArticlesRequest
	QueryApprovedArticlesResponse    = article.QueryApprovedArticlesResponse
	QueryPendingArticlesRequest      = article.QueryPendingArticlesRequest
	QueryPendingArticlesResponse     = article.QueryPendingArticlesResponse
	QueryRejectedArticlesRequest     = article.QueryRejectedArticlesRequest
	QueryRejectedArticlesResponse    = article.QueryRejectedArticlesResponse
	RecommendArticlesRequest         = article.RecommendArticlesRequest
	RecommendArticlesResponse        = article.RecommendArticlesResponse
	Reply                            = article.Reply
	ReplyCommentRequest              = article.ReplyCommentRequest
	ReplyCommentResponse             = article.ReplyCommentResponse
	ReportArticleRequest             = article.ReportArticleRequest
	ReportArticleResponse            = article.ReportArticleResponse
	ReviewArticleRequest             = article.ReviewArticleRequest
	ReviewArticleResponse            = article.ReviewArticleResponse
	SaveDraftArticleRequest          = article.SaveDraftArticleRequest
	SaveDraftArticleResponse         = article.SaveDraftArticleResponse
	ShareArticleRequest              = article.ShareArticleRequest
	ShareArticleResponse             = article.ShareArticleResponse
	UpdateActionRequest              = article.UpdateActionRequest
	UpdateActionResponse             = article.UpdateActionResponse
	UserInfoBase                     = article.UserInfoBase
	UserInfoDetail                   = article.UserInfoDetail
	ViewHistoryRequest               = article.ViewHistoryRequest
	ViewHistoryResponse              = article.ViewHistoryResponse

	Comment interface {
		// 获取楼主评论
		GetCommentList(ctx context.Context, in *GetCommentListRequest, opts ...grpc.CallOption) (*GetCommentListResponse, error)
		// 获取回复评论
		GetReplyComment(ctx context.Context, in *GetReplyCommentRequest, opts ...grpc.CallOption) (*GetReplyCommentResponse, error)
		// 发布评论信息
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
		// 回复评论信息
		ReplyComment(ctx context.Context, in *ReplyCommentRequest, opts ...grpc.CallOption) (*ReplyCommentResponse, error)
		// 点赞/取消点赞评论
		LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error)
		// 获取叶子节点的数量
		GetCommentLeafCount(ctx context.Context, in *GetCommentLeafCountRequest, opts ...grpc.CallOption) (*GetCommentLeafCountResponse, error)
		// 获取评论点赞的数量
		GetLikeCommentCount(ctx context.Context, in *GetLikeCommentCountRequest, opts ...grpc.CallOption) (*GetLikeCommentCountResponse, error)
		CheckIfUserLikedComment(ctx context.Context, in *CheckIfUserLikedCommentRequest, opts ...grpc.CallOption) (*CheckIfUserLikedCommentResponse, error)
	}

	defaultComment struct {
		cli zrpc.Client
	}
)

func NewComment(cli zrpc.Client) Comment {
	return &defaultComment{
		cli: cli,
	}
}

// 获取楼主评论
func (m *defaultComment) GetCommentList(ctx context.Context, in *GetCommentListRequest, opts ...grpc.CallOption) (*GetCommentListResponse, error) {
	client := article.NewCommentClient(m.cli.Conn())
	return client.GetCommentList(ctx, in, opts...)
}

// 获取回复评论
func (m *defaultComment) GetReplyComment(ctx context.Context, in *GetReplyCommentRequest, opts ...grpc.CallOption) (*GetReplyCommentResponse, error) {
	client := article.NewCommentClient(m.cli.Conn())
	return client.GetReplyComment(ctx, in, opts...)
}

// 发布评论信息
func (m *defaultComment) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	client := article.NewCommentClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

// 回复评论信息
func (m *defaultComment) ReplyComment(ctx context.Context, in *ReplyCommentRequest, opts ...grpc.CallOption) (*ReplyCommentResponse, error) {
	client := article.NewCommentClient(m.cli.Conn())
	return client.ReplyComment(ctx, in, opts...)
}

// 点赞/取消点赞评论
func (m *defaultComment) LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error) {
	client := article.NewCommentClient(m.cli.Conn())
	return client.LikeComment(ctx, in, opts...)
}

// 获取叶子节点的数量
func (m *defaultComment) GetCommentLeafCount(ctx context.Context, in *GetCommentLeafCountRequest, opts ...grpc.CallOption) (*GetCommentLeafCountResponse, error) {
	client := article.NewCommentClient(m.cli.Conn())
	return client.GetCommentLeafCount(ctx, in, opts...)
}

// 获取评论点赞的数量
func (m *defaultComment) GetLikeCommentCount(ctx context.Context, in *GetLikeCommentCountRequest, opts ...grpc.CallOption) (*GetLikeCommentCountResponse, error) {
	client := article.NewCommentClient(m.cli.Conn())
	return client.GetLikeCommentCount(ctx, in, opts...)
}

func (m *defaultComment) CheckIfUserLikedComment(ctx context.Context, in *CheckIfUserLikedCommentRequest, opts ...grpc.CallOption) (*CheckIfUserLikedCommentResponse, error) {
	client := article.NewCommentClient(m.cli.Conn())
	return client.CheckIfUserLikedComment(ctx, in, opts...)
}
