// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: post.proto

package server

import (
	"context"

	"github.com/krace-tx/emo_trash/app/rpc/post/internal/logic/post"
	"github.com/krace-tx/emo_trash/app/rpc/post/internal/svc"
	"github.com/krace-tx/emo_trash/app/rpc/post/pb"
)

type PostServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPostServer
}

func NewPostServer(svcCtx *svc.ServiceContext) *PostServer {
	return &PostServer{
		svcCtx: svcCtx,
	}
}

// 发布帖子
func (s *PostServer) CreatePost(ctx context.Context, in *pb.CreatePostReq) (*pb.CreatePostResp, error) {
	l := postlogic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

// 更新帖子
func (s *PostServer) UpdatePost(ctx context.Context, in *pb.UpdatePostReq) (*pb.CommonResp, error) {
	l := postlogic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

// 删除帖子
func (s *PostServer) DeletePost(ctx context.Context, in *pb.DeletePostReq) (*pb.CommonResp, error) {
	l := postlogic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

// 获取帖子详情
func (s *PostServer) GetPostDetail(ctx context.Context, in *pb.GetPostDetailReq) (*pb.GetPostDetailResp, error) {
	l := postlogic.NewGetPostDetailLogic(ctx, s.svcCtx)
	return l.GetPostDetail(in)
}

// 帖子列表
func (s *PostServer) ListPosts(ctx context.Context, in *pb.ListPostsReq) (*pb.ListPostsResp, error) {
	l := postlogic.NewListPostsLogic(ctx, s.svcCtx)
	return l.ListPosts(in)
}

// 点赞/取消点赞
func (s *PostServer) LikePost(ctx context.Context, in *pb.LikePostReq) (*pb.CommonResp, error) {
	l := postlogic.NewLikePostLogic(ctx, s.svcCtx)
	return l.LikePost(in)
}

// 收藏/取消收藏
func (s *PostServer) StarPost(ctx context.Context, in *pb.StarPostReq) (*pb.CommonResp, error) {
	l := postlogic.NewStarPostLogic(ctx, s.svcCtx)
	return l.StarPost(in)
}

// 创建评论
func (s *PostServer) CreateComment(ctx context.Context, in *pb.CreateCommentReq) (*pb.CommonResp, error) {
	l := postlogic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

// 删除评论
func (s *PostServer) DeleteComment(ctx context.Context, in *pb.DeleteCommentReq) (*pb.CommonResp, error) {
	l := postlogic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

// 评论列表
func (s *PostServer) ListComments(ctx context.Context, in *pb.ListCommentsReq) (*pb.ListCommentsResp, error) {
	l := postlogic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}

// 我发布的帖子列表
func (s *PostServer) ListMyPosts(ctx context.Context, in *pb.ListMyPostsReq) (*pb.ListPostsResp, error) {
	l := postlogic.NewListMyPostsLogic(ctx, s.svcCtx)
	return l.ListMyPosts(in)
}

// 我收藏的帖子列表
func (s *PostServer) ListStarredPosts(ctx context.Context, in *pb.ListStarredPostsReq) (*pb.ListPostsResp, error) {
	l := postlogic.NewListStarredPostsLogic(ctx, s.svcCtx)
	return l.ListStarredPosts(in)
}
